import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { access, readFile } from 'node:fs/promises';
import { test } from 'node:test';
import path from 'node:path';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';

const execFileAsync = promisify(execFile);

const repositoryRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../..'
);

const repositoryFile = (relativePath: string): string =>
  path.join(repositoryRoot, relativePath);

const readJson = async (relativePath: string): Promise<Record<string, any>> =>
  JSON.parse(await readFile(repositoryFile(relativePath), 'utf8'));

test('package manifests expose one agent-readable prerelease identity', async () => {
  const version = '0.1.0-preview.1';
  const rootPackage = await readJson('package.json');
  const serverPackage = await readJson('apps/server/package.json');
  const webPackage = await readJson('apps/web/package.json');
  const lockfile = await readJson('package-lock.json');

  assert.equal(rootPackage.name, 'ai-app-builder-foundation');
  assert.equal(rootPackage.version, version);
  assert.equal(rootPackage.private, true);
  assert.equal(rootPackage.license, 'Apache-2.0');
  assert.equal(
    rootPackage.repository.url,
    'git+https://github.com/leedj8886/ai-app-builder-foundation.git'
  );
  assert.deepEqual(rootPackage.keywords, [
    'ai-app-builder',
    'coding-agent',
    'build-verification',
    'self-hosted',
    'prompt-to-app'
  ]);

  assert.equal(serverPackage.name, '@ai-app-builder-foundation/server');
  assert.equal(webPackage.name, '@ai-app-builder-foundation/web');
  assert.match(serverPackage.scripts.test, /run-node-tests\.mjs/);
  assert.match(serverPackage.scripts['test:integration'], /run-node-tests\.mjs/);
  assert.match(webPackage.scripts.test, /run-node-tests\.mjs/);
  await access(repositoryFile('scripts/run-node-tests.mjs'));
  assert.equal(
    rootPackage.optionalDependencies['@rollup/rollup-linux-x64-gnu'],
    '4.60.0'
  );
  assert.equal(
    lockfile.packages['node_modules/@rollup/rollup-linux-x64-gnu'].version,
    '4.60.0'
  );

  for (const packageManifest of [serverPackage, webPackage]) {
    assert.equal(packageManifest.version, version);
    assert.equal(packageManifest.private, true);
    assert.equal(packageManifest.license, 'Apache-2.0');
    assert.doesNotMatch(packageManifest.name, /v0|kimi|deepseek/i);
  }

  assert.equal(lockfile.name, rootPackage.name);
  assert.equal(lockfile.version, version);
  assert.equal(lockfile.packages[''].name, rootPackage.name);
  assert.equal(lockfile.packages[''].version, version);
  assert.equal(lockfile.packages['apps/server'].name, serverPackage.name);
  assert.equal(lockfile.packages['apps/server'].version, version);
  assert.equal(lockfile.packages['apps/web'].name, webPackage.name);
  assert.equal(lockfile.packages['apps/web'].version, version);
});

test('public product surfaces use the AI App Builder Foundation brand', async () => {
  const surfaceFiles = [
    'apps/web/index.html',
    'apps/web/src/components/BrandMark.tsx',
    'apps/web/src/components/MessageList.tsx',
    'apps/web/src/components/ui/Sidebar.tsx',
    'apps/web/src/lib/appBuilderWorkspace.ts',
    'apps/web/src/pages/ChatHistoryPage.tsx',
    'apps/web/src/pages/Register.tsx',
    'apps/web/src/pages/AppBuilderPage.tsx'
  ];
  const surfaces = await Promise.all(
    surfaceFiles.map(relativePath => readFile(repositoryFile(relativePath), 'utf8'))
  );
  const combined = surfaces.join('\n');

  assert.match(combined, /AI App Builder Foundation/);
  assert.doesNotMatch(
    combined,
    /v0 by kimi|Generated by v0|让 v0 构建|v0-clone\.vercel\.app|Deploy to Vercel|Vercel-style|aria-label="v0 home"/i
  );
});

test('workspace does not expose unimplemented publishing capabilities', async () => {
  const workspace = await readFile(
    repositoryFile('apps/web/src/pages/AppBuilderPage.tsx'),
    'utf8'
  );

  assert.doesNotMatch(
    workspace,
    /Repo sync|Sync with repo|Publish|Deploy(?:ment)? planned|Deploy to|open pull request|mocked deployment/i
  );
  assert.doesNotMatch(workspace, /['"]deploy['"]/);
});

test('repository contains the approved open-source governance files', async () => {
  const requiredFiles = [
    'LICENSE',
    'CONTRIBUTING.md',
    'CODE_OF_CONDUCT.md',
    'SECURITY.md',
    'SUPPORT.md',
    'ROADMAP.md'
  ];

  await Promise.all(
    requiredFiles.map(relativePath => access(repositoryFile(relativePath)))
  );

  const license = await readFile(repositoryFile('LICENSE'), 'utf8');
  assert.match(license, /Apache License\s+Version 2\.0, January 2004/);
  assert.match(license, /http:\/\/www\.apache\.org\/licenses\//);

  const contributing = await readFile(
    repositoryFile('CONTRIBUTING.md'),
    'utf8'
  );
  assert.match(contributing, /npm run test:readiness/);
  assert.match(contributing, /npm run test:smoke/);
  assert.match(contributing, /应用层 Agent 框架.*默认不进入核心包/s);
  assert.match(contributing, /独立、可选的 Adapter/);
  assert.match(
    contributing,
    /默认启动、测试、构建或自托管流程的前置条件/
  );

  const security = await readFile(repositoryFile('SECURITY.md'), 'utf8');
  assert.match(security, /不要在公开 Issue 中披露/);

  const conduct = await readFile(
    repositoryFile('CODE_OF_CONDUCT.md'),
    'utf8'
  );
  assert.match(conduct, /开放、专业、尊重事实/);

  const support = await readFile(repositoryFile('SUPPORT.md'), 'utf8');
  assert.match(support, /Developer Preview/);

  const roadmap = await readFile(repositoryFile('ROADMAP.md'), 'utf8');
  assert.match(roadmap, /帮助开发团队搭建自己的 AI App Builder/);
  assert.match(roadmap, /## 长期架构护栏/);
  assert.match(roadmap, /TypeScript Native/);
  assert.match(roadmap, /Framework-Agnostic Core/);
  assert.match(roadmap, /项目自有接口/);
});

test('environment examples document the real runtime configuration', async () => {
  const rootEnv = await readFile(repositoryFile('.env.example'), 'utf8');
  const serverEnv = await readFile(
    repositoryFile('apps/server/.env.example'),
    'utf8'
  );
  const webEnv = await readFile(
    repositoryFile('apps/web/.env.example'),
    'utf8'
  );

  for (const key of [
    'JWT_SECRET',
    'PREVIEW_PUBLIC_ORIGIN',
    'DEEPSEEK_API_KEY',
    'DEEPSEEK_BASE_URL',
    'DEEPSEEK_MODEL',
    'AGENT_MODEL',
    'AGENT_DEFAULT_MODEL_ID',
    'AGENT_MODELS_JSON',
    'AGENT_MAX_REPAIR_ATTEMPTS',
    'AGENT_VALIDATION_EXECUTOR',
    'AGENT_VALIDATION_DEPENDENCY_CACHE_ROOT',
    'SANDBOX_RECONCILE_INTERVAL_MS',
    'SANDBOX_HEARTBEAT_INTERVAL_MS',
    'SANDBOX_HEARTBEAT_TIMEOUT_MS'
  ]) {
    assert.match(rootEnv, new RegExp(`^${key}=`, 'm'));
  }

  assert.match(serverEnv, /^REDIS_URL=/m);
  assert.match(serverEnv, /^PREVIEW_PUBLIC_ORIGIN=/m);
  assert.match(serverEnv, /^DEEPSEEK_API_KEY=/m);
  assert.match(serverEnv, /^AGENT_DEFAULT_MODEL_ID=/m);
  assert.match(serverEnv, /^AGENT_MODELS_JSON=/m);
  assert.match(serverEnv, /^AGENT_VALIDATION_EXECUTOR=legacy$/m);
  assert.match(serverEnv, /^SANDBOX_PROVIDER=fake$/m);
  assert.match(serverEnv, /^SANDBOX_LOCAL_ENABLED=false$/m);
  assert.match(serverEnv, /^SANDBOX_RECONCILE_INTERVAL_MS=30000$/m);
  assert.match(serverEnv, /^SANDBOX_HEARTBEAT_INTERVAL_MS=10000$/m);
  assert.match(serverEnv, /^SANDBOX_HEARTBEAT_TIMEOUT_MS=45000$/m);
  assert.doesNotMatch(serverEnv, /^OPENAI_API_KEY=/m);
  assert.match(webEnv, /^VITE_API_URL=/m);

  for (const contents of [rootEnv, serverEnv, webEnv]) {
    assert.doesNotMatch(contents, /sk-[A-Za-z0-9_-]{16,}/);
  }
});

test('tracked text files do not expose workstation-specific home paths', async () => {
  const { stdout } = await execFileAsync('git', ['ls-files', '-z'], {
    cwd: repositoryRoot,
    encoding: 'utf8'
  });
  const trackedFiles = stdout.split('\0').filter(Boolean);
  const offenders: string[] = [];

  await Promise.all(trackedFiles.map(async relativePath => {
    const contents = await readFile(repositoryFile(relativePath));
    if (contents.includes(0)) return;

    const text = contents.toString('utf8');
    if (/\/Users\/[^/\s]+\/|[A-Za-z]:\\Users\\[^\\\s]+\\/i.test(text)) {
      offenders.push(relativePath);
    }
  }));

  assert.deepEqual(offenders.sort(), []);
});

test('README presents the platform-builder positioning and valid core docs', async () => {
  const readme = await readFile(repositoryFile('README.md'), 'utf8');

  assert.match(readme, /帮助开发团队搭建自己的 AI App Builder/);
  assert.match(readme, /不只是生成代码，而是生成能够通过真实构建的代码/);
  assert.doesNotMatch(readme, /Developer Preview：/);
  assert.doesNotMatch(readme, /无官方关系/);
  assert.doesNotMatch(readme, /历史开发环境中的/);
  assert.match(readme, /TypeScript Native/);
  assert.match(readme, /Framework-Agnostic Core/);
  assert.match(readme, /LangChain、LangGraph、AI SDK/);
  assert.match(readme, /独立、可选的 Adapter/);
  assert.match(readme, /规划.*生成.*类型检查.*生产构建.*诊断.*修复.*快照/s);
  assert.match(readme, /AGENT_VALIDATION_EXECUTOR/);
  assert.match(readme, /simulated.*不能生成.*Snapshot/s);
  assert.doesNotMatch(readme, /尚未把 Agent Worker 校验切换到 Sandbox/);
  assert.doesNotMatch(readme, /类似于 v0\.dev/);

  for (const relativePath of [
    'docs/architecture.md',
    'docs/troubleshooting.md',
    'docs/model-management.md',
    'CONTRIBUTING.md',
    'SECURITY.md',
    'ROADMAP.md'
  ]) {
    await access(repositoryFile(relativePath));
    assert.match(readme, new RegExp(
      relativePath.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    ));
  }
});

test('repository includes contribution templates and a reproducible example', async () => {
  const requiredFiles = [
    '.github/ISSUE_TEMPLATE/bug_report.yml',
    '.github/ISSUE_TEMPLATE/feature_request.yml',
    '.github/ISSUE_TEMPLATE/config.yml',
    '.github/PULL_REQUEST_TEMPLATE.md',
    '.github/workflows/ci.yml',
    'docker-compose.local-sandbox.yml',
    'docs/assets/github-social-preview.png',
    'docs/examples/verified-dashboard.md',
    'docs/github-repository-setup.md',
    'docs/release-checklist.md',
    'docs/releases/v0.1.0-preview.1.md'
  ];

  await Promise.all(
    requiredFiles.map(relativePath => access(repositoryFile(relativePath)))
  );

  const example = await readFile(
    repositoryFile('docs/examples/verified-dashboard.md'),
    'utf8'
  );
  assert.match(example, /生成一个运营 Dashboard/);
  assert.match(example, /Add a compact activity section/);

  const checklist = await readFile(
    repositoryFile('docs/release-checklist.md'),
    'utf8'
  );
  assert.match(checklist, /npm run test:smoke/);
  assert.match(checklist, /四名测试者/);
  assert.doesNotMatch(checklist, /无官方关系/);

  const previewRelease = await readFile(
    repositoryFile('docs/releases/v0.1.0-preview.1.md'),
    'utf8'
  );
  assert.match(previewRelease, /AI App Builder Foundation v0\.1\.0-preview\.1 — Build-Verified Foundation/);
  assert.match(previewRelease, /Developer Preview/);
  assert.match(previewRelease, /尚未创建 GitHub Release/);
  assert.match(previewRelease, /ai-app-builder-foundation@0\.1\.0-preview\.1/);
  assert.match(previewRelease, /private: true/);
  assert.doesNotMatch(
    previewRelease,
    /v0-by-kimi|open-v0|\/v0\/chats|无官方关系/
  );

  const workflow = await readFile(
    repositoryFile('.github/workflows/ci.yml'),
    'utf8'
  );
  assert.match(workflow, /actions\/checkout@v7/);
  assert.match(workflow, /actions\/setup-node@v7/);
  assert.match(workflow, /npm run test:readiness/);
  assert.match(workflow, /npm run test:integration/);
  assert.match(workflow, /docker compose --env-file \.env\.example config --quiet/);

  const socialPreview = await readFile(
    repositoryFile('docs/assets/github-social-preview.png')
  );
  assert.deepEqual([...socialPreview.subarray(0, 8)], [
    0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a
  ]);
  assert.equal(socialPreview.readUInt32BE(16), 1280);
  assert.equal(socialPreview.readUInt32BE(20), 640);

  const localSandboxCompose = await readFile(
    repositoryFile('docker-compose.local-sandbox.yml'),
    'utf8'
  );
  assert.match(localSandboxCompose, /AGENT_VALIDATION_EXECUTOR:\s*sandbox/);
  assert.match(localSandboxCompose, /SANDBOX_PROVIDER:\s*local/);
  assert.match(localSandboxCompose, /NODE_ENV:\s*development/);
});

test('architecture keeps the core independent from application agent frameworks', async () => {
  const architecture = await readFile(
    repositoryFile('docs/architecture.md'),
    'utf8'
  );

  assert.match(architecture, /## 核心边界/);
  assert.match(
    architecture,
    /Model Provider.*Agent Runtime.*Tool Registry.*Run.*Event State.*Workspace Snapshot.*Validate.*Repair.*Preview/s
  );
  assert.match(
    architecture,
    /核心不依赖 LangChain、LangGraph、AI SDK 等应用层 Agent 框架/
  );
  assert.match(architecture, /独立、可选的 Adapter/);
});
