import { GenerationResult } from './types';

const dependencies = {
  '@vitejs/plugin-react': '^4.2.1',
  vite: '^5.1.4',
  react: '^18.2.0',
  'react-dom': '^18.2.0',
  'lucide-react': '^0.344.0'
};

const devDependencies = {
  '@types/react': '^18.2.56',
  '@types/react-dom': '^18.2.19',
  typescript: '^5.4.0'
};

const scripts = {
  dev: 'vite',
  build: 'tsc && vite build',
  'type-check': 'tsc --noEmit'
};

export const buildPhaseTwoGeneration = (prompt: string): GenerationResult => {
  const normalizedPrompt = prompt.trim();
  const title = normalizedPrompt || 'Generated v0 App';
  const packageJson = {
    scripts,
    dependencies,
    devDependencies
  };

  return {
    message: `Generated a React TypeScript snapshot for: ${title}`,
    dependencies,
    devDependencies,
    operations: [
      {
        type: 'create',
        path: 'index.html',
        content: `<div id="root"></div>\n<script type="module" src="/src/main.tsx"></script>\n`
      },
      {
        type: 'create',
        path: 'package.json',
        content: `${JSON.stringify(packageJson, null, 2)}\n`
      },
      {
        type: 'create',
        path: 'README.md',
        content: `# ${title}\n\nGenerated by the Phase 2 TypeScript agent snapshot pipeline.\n`
      },
      {
        type: 'create',
        path: 'src/App.tsx',
        content: `import { Rocket, Sparkles } from 'lucide-react';\n\nconst prompt = ${JSON.stringify(title)};\n\nexport default function App() {\n  return (\n    <main className="min-h-screen bg-neutral-950 px-6 py-10 text-white">\n      <section className="mx-auto flex max-w-5xl flex-col gap-8 rounded-2xl border border-white/10 bg-white/5 p-8 shadow-2xl">\n        <div className="flex items-center gap-3 text-sm text-orange-300">\n          <Sparkles className="h-5 w-5" />\n          Phase 2 snapshot output\n        </div>\n        <div className="space-y-4">\n          <p className="text-sm uppercase tracking-wide text-neutral-400">Prompt</p>\n          <h1 className="text-4xl font-semibold leading-tight">{prompt}</h1>\n          <p className="max-w-2xl text-neutral-300">\n            This file tree was created through structured file operations and saved as a project snapshot.\n          </p>\n        </div>\n        <button className="inline-flex h-10 w-fit items-center gap-2 rounded-lg bg-white px-4 text-sm font-medium text-neutral-950">\n          <Rocket className="h-4 w-4" />\n          Preview snapshot\n        </button>\n      </section>\n    </main>\n  );\n}\n`
      },
      {
        type: 'create',
        path: 'src/index.css',
        content: `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\nbody {\n  margin: 0;\n  font-family: Inter, ui-sans-serif, system-ui, sans-serif;\n}\n`
      },
      {
        type: 'create',
        path: 'src/main.tsx',
        content: `import React from 'react';\nimport { createRoot } from 'react-dom/client';\nimport App from './App';\nimport './index.css';\n\ncreateRoot(document.getElementById('root')!).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>\n);\n`
      }
    ]
  };
};
