issuer: http://localhost:5556/dex

storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db

web:
  http: 0.0.0.0:5556
  allowedOrigins:
    - "*"
  allowedHeaders:
    - x-requested-with

staticClients:
  - id: daytona
    name: Daytona
    public: true
    redirectURIs:
      - http://localhost:3010
      - http://localhost:3010/api/oauth2-redirect.html

enablePasswordDB: true
staticPasswords:
  - email: dev@daytona.io
    # Local development only. The password is "password".
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: admin
    userID: "1234"
