import { FormEvent, useEffect, useMemo, useRef, useState } from 'react'
import {
  ArrowRight,
  CheckCircle2,
  ChevronDown,
  Code2,
  Copy,
  Database,
  Download,
  ExternalLink,
  Eye,
  FileCode2,
  Gamepad2,
  Github,
  Grid2X2,
  Heart,
  Image,
  LineChart,
  Mail,
  Menu,
  Mic,
  Monitor,
  Palette,
  RefreshCw,
  Rocket,
  Search,
  Settings2,
  SlidersHorizontal,
  Sparkles,
  Square,
  Terminal,
  UploadCloud,
  Upload,
  Users,
  Wand2,
  X,
  Zap,
} from 'lucide-react'
import row01 from '@/assets/v0/template-row01.png'
import row02 from '@/assets/v0/template-row02.png'
import iosLight from '@/assets/v0/ios-light.png'
import { agentApi, authApi, projectApi } from '@/services/api'
import { monitorAgentRun } from '@/services/agentRunMonitor'
import {
  applyAgentEvent,
  applyAgentRunDetail,
  applyRunHistory,
  applySnapshotList,
  applyWorkspaceSnapshot,
  createInitialWorkspaceState,
  failApiGeneration,
  isCancellableRunId,
  selectTemplate,
  startApiGeneration,
  switchPanel,
  suggestionPrompts,
  templates,
  type Panel,
  type SnapshotFile,
  type Template,
} from '@/lib/v0Workspace'

const templateImages: Record<Template['image'], string> = {
  row01,
  row02,
  ios: iosLight,
}

const categoryFilters: Array<{
  id: 'all' | Template['category']
  label: string
  icon: typeof Grid2X2
}> = [
  { id: 'apps', label: 'Apps and Games', icon: Gamepad2 },
  { id: 'landing', label: 'Landing Pages', icon: Monitor },
  { id: 'components', label: 'Components', icon: Grid2X2 },
  { id: 'dashboard', label: 'Dashboards', icon: LineChart },
]

const panelTabs: Array<{
  id: Panel
  label: string
  icon: typeof Eye
}> = [
  { id: 'preview', label: 'Preview', icon: Eye },
  { id: 'code', label: 'Code', icon: Code2 },
  { id: 'design', label: 'Design', icon: SlidersHorizontal },
  { id: 'deploy', label: 'Deploy', icon: Rocket },
]

const promptIcons = {
  'Contact Form': Mail,
  'Image Editor': Image,
  'Mini Game': Gamepad2,
  'Finance Calculator': LineChart,
}

const integrationItems = [
  'GitHub repo sync',
  'Supabase database',
  'Vercel Blob uploads',
  'Stripe checkout',
  'AI SDK streaming',
]

const sampleCode = `import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export default function GeneratedApp() {
  return (
    <main className="min-h-screen bg-white text-neutral-950">
      <section className="mx-auto grid max-w-6xl gap-6 px-6 py-10 lg:grid-cols-[1.2fr_0.8fr]">
        <Card className="rounded-lg border-neutral-200">
          <CardContent className="space-y-4 p-6">
            <p className="text-sm text-neutral-500">Generated by v0</p>
            <h1 className="text-3xl font-semibold">Production-ready interface</h1>
            <Button>Publish to Vercel</Button>
          </CardContent>
        </Card>
      </section>
    </main>
  )
}`

const getErrorMessage = (error: unknown) => {
  const apiError = error as {
    response?: { data?: { error?: string; message?: string } }
    message?: string
  }

  return apiError.response?.data?.error ?? apiError.response?.data?.message ?? apiError.message ?? 'Agent request failed'
}

const isAbortError = (error: unknown): boolean =>
  error instanceof Error && error.name === 'AbortError'

const createDemoProject = async (prompt: string) => {
  if (!localStorage.getItem('token')) {
    const unique = `${Date.now()}-${Math.random().toString(16).slice(2)}`
    const authResponse = await authApi.register(
      `phase5-${unique}@v0.local`,
      'password123',
      'Phase Five Demo',
    )
    localStorage.setItem('token', authResponse.data.token)
  }

  const projectResponse = await projectApi.create({
    name: `v0 Snapshot ${new Date().toLocaleTimeString()}`,
    description: prompt,
    settings: {
      framework: 'react',
      styling: 'tailwind',
      uiLibrary: 'shadcn',
    },
  })

  return projectResponse.data.project._id as string
}

export function V0Clone() {
  const [workspace, setWorkspace] = useState(createInitialWorkspaceState)
  const [draftPrompt, setDraftPrompt] = useState('')
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)
  const [modelOpen, setModelOpen] = useState(false)
  const [model, setModel] = useState('Mock provider')
  const [category, setCategory] = useState<'all' | Template['category']>('all')
  const [designMode, setDesignMode] = useState(true)
  const [deployOpen, setDeployOpen] = useState(false)
  const [copied, setCopied] = useState(false)
  const [projectId, setProjectId] = useState(
    () => localStorage.getItem('v0.activeProjectId') ?? '',
  )
  const refreshRequestRef = useRef(0)
  const rollbackInFlightRef = useRef(false)
  const monitorControllerRef = useRef<AbortController | null>(null)
  const submissionInFlightRef = useRef(false)
  const submissionIdRef = useRef(0)

  const visibleTemplates = useMemo(
    () => templates.filter((template) => category === 'all' || template.category === category),
    [category],
  )

  const selectedTemplate = useMemo(
    () => templates.find((template) => template.id === workspace.selectedTemplateId) ?? templates[0],
    [workspace.selectedTemplateId],
  )

  const currentPrompt = workspace.prompt || draftPrompt || selectedTemplate.prompt
  const selectedSnapshotFile = workspace.snapshot?.files.find(
    (file) => file.path === workspace.snapshot?.selectedFilePath,
  ) ?? workspace.snapshot?.files[0]
  const currentCode = selectedSnapshotFile?.content ?? sampleCode
  const currentFileName = selectedSnapshotFile?.path ?? 'generated-app.tsx'

  const refreshProjectData = async (id: string) => {
    const requestId = ++refreshRequestRef.current
    const [runsResponse, snapshotsResponse] = await Promise.all([
      agentApi.getRuns(id),
      projectApi.getSnapshots(id),
    ])
    if (requestId !== refreshRequestRef.current) {
      return null
    }
    setWorkspace((state) =>
      applySnapshotList(
        applyRunHistory(state, runsResponse.data.runs),
        snapshotsResponse.data.snapshots,
      ),
    )
    return snapshotsResponse.data.snapshots
  }

  useEffect(() => {
    if (!projectId || !localStorage.getItem('token')) return

    void (async () => {
      try {
        const snapshots = await refreshProjectData(projectId)
        const activeSnapshotId = snapshots?.find((snapshot) => snapshot.isActive)?.id
        if (activeSnapshotId) {
          const snapshotResponse = await projectApi.getSnapshot(projectId, activeSnapshotId)
          setWorkspace((state) =>
            state.snapshots.find((snapshot) => snapshot.isActive)?.id === activeSnapshotId
              ? applyWorkspaceSnapshot(state, snapshotResponse.data.snapshot)
              : state,
          )
        }
      } catch {
        localStorage.removeItem('v0.activeProjectId')
        setProjectId('')
      }
    })()
  }, [projectId])

  useEffect(() => () => {
    monitorControllerRef.current?.abort()
  }, [])

  const submitPromptToAgent = async (rawPrompt: string) => {
    const prompt = rawPrompt.trim()

    if (!prompt || workspace.generation.status === 'running' || submissionInFlightRef.current) {
      return
    }

    submissionInFlightRef.current = true
    const submissionId = ++submissionIdRef.current

    setDraftPrompt(prompt)
    setWorkspace((state) =>
      startApiGeneration(state, prompt, `pending:${crypto.randomUUID()}`),
    )

    try {
      let activeProjectId = projectId
      if (!activeProjectId) {
        activeProjectId = await createDemoProject(prompt)
        setProjectId(activeProjectId)
        localStorage.setItem('v0.activeProjectId', activeProjectId)
      }
      let mode: 'create' | 'edit' = workspace.snapshot ? 'edit' : 'create'
      if (mode === 'create' && projectId) {
        const projectResponse = await projectApi.getById(activeProjectId)
        mode = projectResponse.data.project.activeSnapshotId ? 'edit' : 'create'
      }
      const runResponse = await agentApi.createRun({
        projectId: activeProjectId,
        prompt,
        mode,
      })

      if (submissionId !== submissionIdRef.current) return

      monitorControllerRef.current?.abort()
      const controller = new AbortController()
      monitorControllerRef.current = controller
      const token = localStorage.getItem('token')
      if (!token) throw new Error('Authentication token is unavailable')

      const runId = runResponse.data.run._id
      setWorkspace((state) => startApiGeneration(state, prompt, runId))
      const detail = await monitorAgentRun({
        runId,
        token,
        signal: controller.signal,
        onEvent: (event) => {
          setWorkspace((state) => applyAgentEvent(state, runId, event))
        },
      })
      setWorkspace((state) => applyAgentRunDetail(state, detail))
      await refreshProjectData(activeProjectId)
    } catch (error) {
      if (!isAbortError(error) && submissionId === submissionIdRef.current) {
        setWorkspace((state) => failApiGeneration(state, getErrorMessage(error)))
      }
    } finally {
      if (submissionId === submissionIdRef.current) {
        submissionInFlightRef.current = false
      }
    }
  }

  const handleCancelRun = async () => {
    const runId = workspace.generation.runId
    if (!isCancellableRunId(runId)) return
    monitorControllerRef.current?.abort()
    monitorControllerRef.current = null
    try {
      const response = await agentApi.cancelRun(runId)
      setWorkspace((state) => applyAgentRunDetail(state, {
        run: response.data.run,
        events: [],
        resultSnapshot: null,
      }))
      if (projectId) await refreshProjectData(projectId)
    } catch (error) {
      setWorkspace((state) => failApiGeneration(state, getErrorMessage(error)))
    }
  }

  const handleBackHome = () => {
    submissionIdRef.current += 1
    submissionInFlightRef.current = false
    monitorControllerRef.current?.abort()
    monitorControllerRef.current = null
    setWorkspace((state) => ({
      ...state,
      screen: 'home',
      prompt: '',
      generation: {
        status: 'idle',
        steps: [],
      },
    }))
  }

  const handleRollback = async (snapshotId: string) => {
    if (!projectId || rollbackInFlightRef.current) return
    rollbackInFlightRef.current = true
    refreshRequestRef.current += 1
    try {
      const response = await projectApi.rollbackSnapshot(projectId, snapshotId)
      setWorkspace((state) => applyWorkspaceSnapshot(state, response.data.snapshot))
      await refreshProjectData(projectId)
    } finally {
      rollbackInFlightRef.current = false
    }
  }

  const handlePromptSubmit = (event?: FormEvent) => {
    event?.preventDefault()
    void submitPromptToAgent(draftPrompt || selectedTemplate.prompt)
  }

  const handleTemplateSelect = (templateId: string) => {
    const next = selectTemplate(workspace, templateId)
    setWorkspace(next)
    setDraftPrompt(next.prompt)
  }

  const handleSuggestion = (label: string) => {
    const prompt = `Build a ${label.toLowerCase()} with polished interactions, responsive states, and production-ready code.`
    setDraftPrompt(prompt)
  }

  const handleCopy = async () => {
    await navigator.clipboard.writeText(currentCode)
    setCopied(true)
    window.setTimeout(() => setCopied(false), 1600)
  }

  const handleDownload = () => {
    const blob = new Blob([currentCode], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const anchor = document.createElement('a')
    anchor.href = url
    anchor.download = currentFileName.split('/').pop() ?? 'generated-app.tsx'
    anchor.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="min-h-screen bg-[#fafafa] text-neutral-950 antialiased">
      <TopNav
        mobileMenuOpen={mobileMenuOpen}
        onToggleMobileMenu={() => setMobileMenuOpen((open) => !open)}
      />

      {workspace.screen === 'home' ? (
        <main className="mx-auto w-full max-w-[1240px] px-3 pb-16 pt-20 sm:px-6 lg:pt-32">
          <section className="mx-auto flex max-w-[720px] flex-col items-center text-center">
            <h1 className="text-[28px] font-semibold leading-tight sm:text-[30px]">
              您想创建什么?
            </h1>

            <form
              className="mt-5 w-full rounded-lg border border-neutral-300 bg-white shadow-sm transition focus-within:border-neutral-500 focus-within:shadow-md"
              onSubmit={handlePromptSubmit}
            >
              <textarea
                value={draftPrompt}
                onChange={(event) => setDraftPrompt(event.target.value)}
                onKeyDown={(event) => {
                  if (event.key === 'Enter' && !event.shiftKey) {
                    event.preventDefault()
                    void submitPromptToAgent(draftPrompt || selectedTemplate.prompt)
                  }
                }}
                placeholder="让 v0 构建..."
                className="h-20 w-full resize-none rounded-t-lg bg-transparent px-4 py-4 text-sm leading-6 text-neutral-800 outline-none placeholder:text-neutral-400 sm:h-[74px]"
              />
              <div className="flex items-center justify-between px-3 pb-3">
                <div className="relative">
                  <button
                    type="button"
                    className="inline-flex h-8 items-center gap-2 rounded-md px-2 text-sm text-neutral-600 hover:bg-neutral-100"
                    onClick={() => setModelOpen((open) => !open)}
                  >
                    <Sparkles className="h-4 w-4 text-orange-500" />
                    {model}
                    <ChevronDown className="h-3.5 w-3.5" />
                  </button>
                  {modelOpen ? (
                    <div className="absolute left-0 top-10 z-20 w-44 rounded-lg border border-neutral-200 bg-white p-1 text-left text-sm shadow-xl">
                      {['Mock provider', 'Fable 5', 'Opus 4.5', 'Fast Build'].map((item) => (
                        <button
                          type="button"
                          key={item}
                          className="flex w-full items-center justify-between rounded-md px-3 py-2 text-neutral-700 hover:bg-neutral-100"
                          onClick={() => {
                            setModel(item)
                            setModelOpen(false)
                          }}
                        >
                          {item}
                          {model === item ? <CheckCircle2 className="h-4 w-4" /> : null}
                        </button>
                      ))}
                    </div>
                  ) : null}
                </div>

                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    className="hidden h-8 w-8 items-center justify-center rounded-md text-neutral-500 hover:bg-neutral-100 sm:inline-flex"
                    aria-label="Upload context"
                  >
                    <Upload className="h-4 w-4" />
                  </button>
                  <button
                    type="button"
                    className="h-8 w-8 rounded-md bg-neutral-950 text-white hover:bg-neutral-800"
                    aria-label="Voice prompt"
                  >
                    <Mic className="mx-auto h-4 w-4" />
                  </button>
                  {draftPrompt.trim() ? (
                    <button
                      type="submit"
                      className="inline-flex h-8 w-8 items-center justify-center rounded-md bg-neutral-950 text-white hover:bg-neutral-800 disabled:cursor-not-allowed disabled:bg-neutral-400"
                      aria-label="Build prompt"
                      disabled={workspace.generation.status === 'running'}
                    >
                      {workspace.generation.status === 'running' ? <RefreshCw className="h-4 w-4 animate-spin" /> : <ArrowRight className="h-4 w-4" />}
                    </button>
                  ) : null}
                </div>
              </div>
            </form>

            <div className="mt-4 flex flex-wrap justify-center gap-2">
              {suggestionPrompts.map((label) => {
                const Icon = promptIcons[label]
                return (
                  <button
                    key={label}
                    className="inline-flex h-8 items-center gap-2 rounded-full border border-neutral-200 bg-white px-3 text-sm text-neutral-600 shadow-sm hover:border-neutral-300 hover:bg-neutral-50"
                    onClick={() => handleSuggestion(label)}
                  >
                    <Icon className="h-4 w-4" />
                    {label}
                  </button>
                )
              })}
              <button
                className="inline-flex h-8 w-8 items-center justify-center rounded-full border border-neutral-200 bg-white text-neutral-600 shadow-sm hover:border-neutral-300 hover:bg-neutral-50"
                aria-label="Refresh suggestions"
                onClick={() => setDraftPrompt('Create a clean AI analytics workspace with charts, files, and deploy controls.')}
              >
                <RefreshCw className="h-4 w-4" />
              </button>
            </div>
          </section>

          <section className="mt-24 sm:mt-32">
            <div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between">
              <h2 className="text-2xl font-semibold">Start with a template</h2>
              <div className="hidden flex-wrap items-center gap-2 sm:flex">
                {categoryFilters.map((filter) => {
                  const Icon = filter.icon
                  const active = category === filter.id
                  return (
                    <button
                      key={filter.id}
                      className={`inline-flex h-8 items-center gap-2 rounded-full border px-3 text-sm ${
                        active
                          ? 'border-neutral-950 bg-neutral-950 text-white'
                          : 'border-neutral-200 bg-white text-neutral-600 hover:bg-neutral-50'
                      }`}
                      onClick={() => setCategory(active ? 'all' : filter.id)}
                    >
                      <Icon className="h-4 w-4" />
                      {filter.label}
                    </button>
                  )
                })}
                <button
                  className="inline-flex h-8 items-center gap-2 rounded-full px-3 text-sm font-medium text-neutral-800 hover:bg-neutral-100"
                  onClick={() => setCategory('all')}
                >
                  Browse all
                  <ArrowRight className="h-4 w-4" />
                </button>
              </div>
            </div>

            <div className="mt-6 grid gap-7 md:grid-cols-2 lg:grid-cols-3">
              {visibleTemplates.map((template) => (
                <TemplateCard
                  key={template.id}
                  template={template}
                  imageSrc={templateImages[template.image]}
                  selected={workspace.selectedTemplateId === template.id}
                  onSelect={() => handleTemplateSelect(template.id)}
                  onBuild={() => {
                    const next = selectTemplate(workspace, template.id)
                    setWorkspace(next)
                    setDraftPrompt(next.prompt)
                    void submitPromptToAgent(next.prompt)
                  }}
                />
              ))}
            </div>
          </section>
        </main>
      ) : (
        <WorkspaceScreen
          prompt={currentPrompt}
          selectedTemplate={selectedTemplate}
          state={workspace}
          designMode={designMode}
          deployOpen={deployOpen}
          copied={copied}
          onBackHome={handleBackHome}
          onSwitchPanel={(panel) => setWorkspace((state) => switchPanel(state, panel))}
          onSelectSnapshotFile={(filePath) =>
            setWorkspace((state) =>
              state.snapshot
                ? {
                    ...state,
                    snapshot: {
                      ...state.snapshot,
                      selectedFilePath: filePath,
                    },
                  }
                : state,
            )
          }
          onToggleDesignMode={() => setDesignMode((enabled) => !enabled)}
          onToggleDeploy={() => setDeployOpen((open) => !open)}
          onCopy={handleCopy}
          onDownload={handleDownload}
          onCancelRun={() => void handleCancelRun()}
          onRollback={(snapshotId) => void handleRollback(snapshotId)}
          currentCode={currentCode}
          currentFileName={currentFileName}
        />
      )}
    </div>
  )
}

function TopNav({
  mobileMenuOpen,
  onToggleMobileMenu,
}: {
  mobileMenuOpen: boolean
  onToggleMobileMenu: () => void
}) {
  return (
    <header className="sticky top-0 z-30 border-b border-neutral-200 bg-[#fafafa]/95 backdrop-blur">
      <div className="mx-auto flex h-12 max-w-[1440px] items-center justify-between px-3 sm:px-4">
        <button className="flex h-8 items-center gap-2 rounded-md text-left" aria-label="v0 home">
          <span className="text-[21px] font-black leading-none tracking-normal">v0</span>
        </button>

        <nav className="hidden items-center gap-6 text-sm text-neutral-600 md:flex">
          <NavMenu label="Templates" items={['Apps and Games', 'Landing Pages', 'Dashboards']} />
          <NavMenu label="Resources" items={['Docs', 'Community', 'Enterprise Guide']} />
          <a className="hover:text-neutral-950" href="#enterprise">Enterprise</a>
          <a className="hover:text-neutral-950" href="#pricing">Pricing</a>
          <a className="hover:text-neutral-950" href="#ios">iOS</a>
          <a className="hover:text-neutral-950" href="#students">Students</a>
          <a className="hover:text-neutral-950" href="#faq">FAQ</a>
        </nav>

        <div className="hidden items-center gap-2 md:flex">
          <button className="h-8 rounded-md border border-neutral-200 bg-white px-3 text-sm hover:bg-neutral-50">
            登录
          </button>
          <button className="h-8 rounded-md bg-neutral-950 px-3 text-sm font-medium text-white hover:bg-neutral-800">
            注册
          </button>
        </div>

        <button
          className="inline-flex h-9 w-9 items-center justify-center rounded-lg border border-neutral-200 bg-white md:hidden"
          onClick={onToggleMobileMenu}
          aria-label="Toggle navigation"
        >
          {mobileMenuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}
        </button>
      </div>

      {mobileMenuOpen ? (
        <div className="border-t border-neutral-200 bg-white p-3 md:hidden">
          {['Templates', 'Resources', 'Enterprise', 'Pricing', 'iOS', 'Students', 'FAQ'].map((item) => (
            <button
              key={item}
              className="flex h-10 w-full items-center justify-between rounded-md px-2 text-sm text-neutral-700 hover:bg-neutral-100"
            >
              {item}
              <ArrowRight className="h-4 w-4" />
            </button>
          ))}
        </div>
      ) : null}
    </header>
  )
}

function NavMenu({ label, items }: { label: string; items: string[] }) {
  const [open, setOpen] = useState(false)

  return (
    <div className="relative">
      <button
        className="inline-flex items-center gap-1 hover:text-neutral-950"
        onClick={() => setOpen((value) => !value)}
      >
        {label}
        <ChevronDown className="h-3.5 w-3.5" />
      </button>
      {open ? (
        <div className="absolute left-1/2 top-8 w-52 -translate-x-1/2 rounded-lg border border-neutral-200 bg-white p-1 shadow-xl">
          {items.map((item) => (
            <button
              key={item}
              className="flex w-full items-center justify-between rounded-md px-3 py-2 text-left text-sm text-neutral-700 hover:bg-neutral-100"
              onClick={() => setOpen(false)}
            >
              {item}
              <ArrowRight className="h-4 w-4 text-neutral-400" />
            </button>
          ))}
        </div>
      ) : null}
    </div>
  )
}

function TemplateCard({
  template,
  imageSrc,
  selected,
  onSelect,
  onBuild,
}: {
  template: Template
  imageSrc: string
  selected: boolean
  onSelect: () => void
  onBuild: () => void
}) {
  return (
    <article className="group">
      <button
        className={`block w-full overflow-hidden rounded-lg border text-left transition ${
          selected
            ? 'border-neutral-950 ring-2 ring-neutral-950/10'
            : 'border-neutral-200 hover:border-neutral-300'
        }`}
        onClick={onSelect}
      >
        <div className="aspect-[16/9] bg-neutral-100">
          <img
            src={imageSrc}
            alt=""
            className="h-full w-full object-cover transition duration-300 group-hover:scale-[1.02]"
          />
        </div>
      </button>
      <div className="mt-2 flex items-start gap-3">
        <div className="h-9 w-9 shrink-0 rounded-full border border-neutral-200 bg-neutral-100" />
        <div className="min-w-0 flex-1">
          <h3 className="truncate text-sm font-medium">{template.title}</h3>
          <div className="mt-1 flex items-center gap-3 text-xs text-neutral-500">
            <span className="inline-flex items-center gap-1">
              <Users className="h-3.5 w-3.5" />
              {template.views}
            </span>
            <span className="inline-flex items-center gap-1">
              <Heart className="h-3.5 w-3.5" />
              {template.likes}
            </span>
          </div>
        </div>
        <button
          className="h-8 rounded-md bg-neutral-950 px-3 text-xs font-medium text-white opacity-0 transition hover:bg-neutral-800 group-hover:opacity-100"
          onClick={onBuild}
        >
          Use template
        </button>
      </div>
    </article>
  )
}

function WorkspaceScreen({
  prompt,
  selectedTemplate,
  state,
  designMode,
  deployOpen,
  copied,
  onBackHome,
  onSwitchPanel,
  onSelectSnapshotFile,
  onToggleDesignMode,
  onToggleDeploy,
  onCopy,
  onDownload,
  onCancelRun,
  onRollback,
  currentCode,
  currentFileName,
}: {
  prompt: string
  selectedTemplate: Template
  state: ReturnType<typeof createInitialWorkspaceState>
  designMode: boolean
  deployOpen: boolean
  copied: boolean
  onBackHome: () => void
  onSwitchPanel: (panel: Panel) => void
  onSelectSnapshotFile: (filePath: string) => void
  onToggleDesignMode: () => void
  onToggleDeploy: () => void
  onCopy: () => void
  onDownload: () => void
  onCancelRun: () => void
  onRollback: (snapshotId: string) => void
  currentCode: string
  currentFileName: string
}) {
  const assistantTitle = state.generation.status === 'running'
    ? 'I am creating a project snapshot.'
    : state.generation.status === 'failed'
      ? 'The agent run needs attention.'
      : state.generation.status === 'cancelled'
        ? 'The agent run was cancelled.'
        : 'I built a snapshot-backed preview.'
  const assistantDescription = state.generation.status === 'running'
    ? 'The prompt is running through the local API, Redis queue, worker, and MongoDB snapshot store.'
    : state.generation.status === 'failed'
      ? state.generation.error ?? 'The run did not complete.'
      : state.generation.status === 'cancelled'
        ? 'You can revise the prompt and start another run.'
        : state.snapshot?.summary ?? 'The app includes responsive layout, structured files, code export, repo sync, and a publish flow.'

  return (
    <main className="grid min-h-[calc(100vh-48px)] grid-cols-1 bg-white lg:grid-cols-[272px_1fr]">
      <aside className="hidden border-r border-neutral-200 bg-[#fafafa] lg:flex lg:flex-col">
        <div className="p-3">
          <button
            className="flex h-9 w-full items-center justify-center gap-2 rounded-md bg-neutral-950 text-sm font-medium text-white hover:bg-neutral-800"
            onClick={onBackHome}
          >
            <Sparkles className="h-4 w-4" />
            New chat
          </button>
        </div>
        <div className="border-y border-neutral-200 p-3">
          <div className="relative">
            <Search className="absolute left-3 top-2.5 h-4 w-4 text-neutral-400" />
            <input
              className="h-9 w-full rounded-md border border-neutral-200 bg-white pl-9 pr-3 text-sm outline-none focus:border-neutral-400"
              placeholder="Search chats"
            />
          </div>
        </div>
        <nav className="flex-1 space-y-1 overflow-y-auto p-2">
          <p className="px-2 pb-2 pt-1 text-xs font-medium uppercase text-neutral-400">Recent</p>
          {state.runHistory.map((run, index) => (
            <button
              key={run._id}
              className={`flex w-full items-center gap-2 rounded-md px-2 py-2 text-left text-sm ${
                index === 0 ? 'bg-neutral-200 text-neutral-950' : 'text-neutral-600 hover:bg-neutral-100'
              }`}
            >
              <Terminal className="h-4 w-4 shrink-0" />
              <span className="min-w-0 flex-1 truncate">{run.prompt ?? 'Untitled run'}</span>
              <span className="text-[10px] uppercase text-neutral-400">{run.status}</span>
            </button>
          ))}
        </nav>
        <div className="space-y-1 border-t border-neutral-200 p-2">
          <button className="flex h-9 w-full items-center gap-2 rounded-md px-2 text-sm text-neutral-600 hover:bg-neutral-100">
            <Github className="h-4 w-4" />
            Sync with repo
          </button>
          <button className="flex h-9 w-full items-center gap-2 rounded-md px-2 text-sm text-neutral-600 hover:bg-neutral-100">
            <Settings2 className="h-4 w-4" />
            Settings
          </button>
        </div>
      </aside>

      <section className="flex min-w-0 flex-col">
        <div className="flex h-13 min-h-13 items-center justify-between border-b border-neutral-200 px-3 py-2 sm:px-4">
          <div className="min-w-0">
            <p className="truncate text-sm font-medium">{selectedTemplate.title}</p>
            <p className="truncate text-xs text-neutral-500">{prompt}</p>
          </div>
          <div className="flex items-center gap-2">
            <button className="hidden h-8 items-center gap-2 rounded-md border border-neutral-200 px-3 text-sm text-neutral-700 hover:bg-neutral-50 sm:inline-flex">
              <Github className="h-4 w-4" />
              Sync
            </button>
            <button
              className="h-8 rounded-md bg-neutral-950 px-3 text-sm font-medium text-white hover:bg-neutral-800"
              onClick={onToggleDeploy}
            >
              Publish
            </button>
          </div>
        </div>

        <div className="grid flex-1 grid-cols-1 overflow-hidden xl:grid-cols-[440px_1fr]">
          <section className="flex min-h-[420px] flex-col border-b border-neutral-200 xl:border-b-0 xl:border-r">
            <div className="border-b border-neutral-200 p-4">
              <div className="rounded-lg border border-neutral-200 bg-[#fafafa] p-3">
                <p className="text-sm leading-6 text-neutral-700">{prompt}</p>
              </div>
            </div>

            <div className="flex-1 space-y-4 overflow-y-auto p-4">
              <div className="flex gap-3">
                <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-neutral-950 text-sm font-semibold text-white">
                  v0
                </div>
                <div className="min-w-0 flex-1">
                  <div
                    className="rounded-lg border border-neutral-200 bg-white p-4 shadow-sm"
                    data-testid="agent-generation-status"
                    data-status={state.generation.status}
                  >
                    <p className="text-sm font-medium">{assistantTitle}</p>
                    <p className="mt-2 text-sm leading-6 text-neutral-600">{assistantDescription}</p>
                  </div>
                  {state.generation.status === 'running' &&
                  isCancellableRunId(state.generation.runId) ? (
                    <button
                      className="mt-2 inline-flex h-8 items-center gap-2 rounded-md border border-red-200 px-3 text-xs font-medium text-red-700 hover:bg-red-50"
                      onClick={onCancelRun}
                    >
                      <Square className="h-3 w-3 fill-current" />
                      Stop run
                    </button>
                  ) : null}
                </div>
              </div>

              <div className="rounded-lg border border-neutral-200 bg-white" data-testid="agent-timeline">
                <div className="border-b border-neutral-200 px-4 py-3">
                  <p className="text-sm font-medium">Agent plan</p>
                </div>
                <div className="space-y-1 p-2">
                  {state.generation.steps.map((step) => (
                    <div key={step.id} className="flex gap-3 rounded-md p-2">
                      <div
                        className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full ${
                          step.status === 'active'
                            ? 'bg-orange-100 text-orange-700'
                            : 'bg-emerald-100 text-emerald-700'
                        }`}
                      >
                        {step.status === 'active' ? <Zap className="h-3.5 w-3.5" /> : <CheckCircle2 className="h-3.5 w-3.5" />}
                      </div>
                      <div>
                        <p className="text-sm font-medium">{step.label}</p>
                        <p className="text-xs leading-5 text-neutral-500">{step.detail}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {state.generation.error ? (
                <div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-950">
                  {state.generation.error}
                </div>
              ) : null}

              {state.snapshot ? (
                <div className="rounded-lg border border-neutral-200 bg-white" data-testid="snapshot-history">
                  <div className="border-b border-neutral-200 px-4 py-3">
                    <p className="text-sm font-medium">Project snapshot</p>
                    <p className="mt-1 text-xs text-neutral-500">{state.snapshot.files.length} files saved in MongoDB</p>
                  </div>
                  <div className="space-y-1 p-2">
                    {state.snapshot.files.map((file) => (
                      <button
                        key={file.path}
                        className={`flex w-full items-center gap-2 rounded-md px-2 py-2 text-left text-sm ${
                          state.snapshot?.selectedFilePath === file.path
                            ? 'bg-neutral-950 text-white'
                            : 'text-neutral-700 hover:bg-neutral-100'
                        }`}
                        onClick={() => {
                          onSelectSnapshotFile(file.path)
                          onSwitchPanel('code')
                        }}
                      >
                        <FileCode2 className="h-4 w-4 shrink-0" />
                        <span className="truncate">{file.path}</span>
                      </button>
                    ))}
                  </div>
                  <div className="border-t border-neutral-200 p-3 text-xs text-neutral-600">
                    <p className="font-medium text-neutral-800">
                      Validation: {state.snapshot.validation.status}
                    </p>
                    <div className="mt-2 flex flex-wrap gap-1">
                      {Object.entries(state.snapshot.packageJson.dependencies).map(([name, version]) => (
                        <span key={name} className="rounded bg-neutral-100 px-2 py-1">{name} {version}</span>
                      ))}
                      {Object.entries(state.snapshot.packageJson.devDependencies).map(([name, version]) => (
                        <span key={name} className="rounded bg-blue-50 px-2 py-1 text-blue-700">{name} {version} (dev)</span>
                      ))}
                    </div>
                  </div>
                </div>
              ) : null}

              {state.snapshots.length > 0 ? (
                <div className="rounded-lg border border-neutral-200 bg-white">
                  <div className="border-b border-neutral-200 px-4 py-3 text-sm font-medium">Snapshot history</div>
                  <div className="space-y-2 p-2">
                    {state.snapshots.map((snapshot) => (
                      <div key={snapshot.id} className="flex items-center justify-between gap-2 rounded-md p-2 text-sm">
                        <div className="min-w-0">
                          <p className="truncate font-medium">{snapshot.summary}</p>
                          <p className="text-xs text-neutral-500">
                            {snapshot.fileCount} files · {snapshot.validation.status}
                            {snapshot.isActive ? ' · active' : ''}
                          </p>
                        </div>
                        {!snapshot.isActive ? (
                          <button
                            className="rounded-md border border-neutral-200 px-2 py-1 text-xs hover:bg-neutral-50"
                            onClick={() => onRollback(snapshot.id)}
                          >
                            Restore
                          </button>
                        ) : null}
                      </div>
                    ))}
                  </div>
                </div>
              ) : null}

              <div className="rounded-lg border border-neutral-200 bg-[#fafafa] p-3">
                <p className="text-xs font-medium uppercase text-neutral-400">Integrations</p>
                <div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-1">
                  {integrationItems.map((item) => (
                    <div key={item} className="flex items-center gap-2 rounded-md bg-white px-3 py-2 text-sm text-neutral-700">
                      <CheckCircle2 className="h-4 w-4 text-emerald-600" />
                      {item}
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </section>

          <section className="flex min-w-0 flex-col bg-[#f5f5f5]">
            <div className="flex flex-wrap items-center justify-between gap-3 border-b border-neutral-200 bg-white px-3 py-2">
              <div className="flex rounded-md border border-neutral-200 bg-neutral-100 p-0.5">
                {panelTabs.map((tab) => {
                  const Icon = tab.icon
                  const active = state.activePanel === tab.id
                  return (
                    <button
                      key={tab.id}
                      className={`inline-flex h-8 items-center gap-2 rounded px-3 text-sm ${
                        active ? 'bg-white text-neutral-950 shadow-sm' : 'text-neutral-600 hover:text-neutral-950'
                      }`}
                      onClick={() => onSwitchPanel(tab.id)}
                    >
                      <Icon className="h-4 w-4" />
                      {tab.label}
                    </button>
                  )
                })}
              </div>
              <div className="flex items-center gap-2">
                <button
                  className={`inline-flex h-8 items-center gap-2 rounded-md border px-3 text-sm ${
                    designMode ? 'border-neutral-950 bg-neutral-950 text-white' : 'border-neutral-200 bg-white text-neutral-700'
                  }`}
                  onClick={onToggleDesignMode}
                >
                  <Palette className="h-4 w-4" />
                  Design Mode
                </button>
                <button
                  className="inline-flex h-8 items-center gap-2 rounded-md border border-neutral-200 bg-white px-3 text-sm text-neutral-700 hover:bg-neutral-50"
                  onClick={onCopy}
                >
                  <Copy className="h-4 w-4" />
                  {copied ? 'Copied' : 'Copy'}
                </button>
              </div>
            </div>

            <div className="flex-1 overflow-y-auto p-3 sm:p-5">
              {state.activePanel === 'preview' ? <PreviewPanel selectedTemplate={selectedTemplate} designMode={designMode} /> : null}
              {state.activePanel === 'code' ? (
                <CodePanel
                  files={state.snapshot?.files ?? []}
                  selectedFilePath={state.snapshot?.selectedFilePath ?? null}
                  code={currentCode}
                  fileName={currentFileName}
                  copied={copied}
                  onCopy={onCopy}
                  onDownload={onDownload}
                  onSelectFile={onSelectSnapshotFile}
                />
              ) : null}
              {state.activePanel === 'design' ? <DesignPanel enabled={designMode} onToggle={onToggleDesignMode} /> : null}
              {state.activePanel === 'deploy' ? <DeployPanel open={deployOpen} onToggle={onToggleDeploy} /> : null}
            </div>
          </section>
        </div>
      </section>
    </main>
  )
}

function PreviewPanel({
  selectedTemplate,
  designMode,
}: {
  selectedTemplate: Template
  designMode: boolean
}) {
  return (
    <div className="mx-auto max-w-5xl rounded-lg border border-neutral-200 bg-white shadow-sm">
      <div className="flex items-center justify-between border-b border-neutral-200 px-4 py-2">
        <div className="flex items-center gap-2">
          <span className="h-3 w-3 rounded-full bg-red-400" />
          <span className="h-3 w-3 rounded-full bg-yellow-400" />
          <span className="h-3 w-3 rounded-full bg-emerald-400" />
        </div>
        <div className="hidden min-w-0 max-w-md flex-1 justify-center px-4 sm:flex">
          <div className="truncate rounded-md bg-neutral-100 px-3 py-1 text-xs text-neutral-500">
            preview.v0.local/{selectedTemplate.id}
          </div>
        </div>
        <button className="rounded-md p-1.5 text-neutral-500 hover:bg-neutral-100" aria-label="Open preview">
          <ExternalLink className="h-4 w-4" />
        </button>
      </div>

      <div className="grid gap-6 p-5 lg:grid-cols-[1.15fr_0.85fr]">
        <section className="space-y-6">
          <div className="rounded-lg border border-neutral-200 bg-neutral-950 p-6 text-white">
            <div className="flex items-center justify-between">
              <p className="text-sm text-neutral-400">AI generated</p>
              <span className="rounded-full bg-white/10 px-3 py-1 text-xs">Live</span>
            </div>
            <h2 className="mt-12 max-w-xl text-4xl font-semibold leading-tight">
              {selectedTemplate.title}
            </h2>
            <p className="mt-4 max-w-lg text-sm leading-6 text-neutral-300">
              A production-flavored interface with responsive sections, connected
              data cards, and publish-ready controls.
            </p>
            <div className="mt-6 flex flex-wrap gap-2">
              <button className="h-9 rounded-md bg-white px-4 text-sm font-medium text-neutral-950">
                Start free
              </button>
              <button className="h-9 rounded-md border border-white/20 px-4 text-sm text-white">
                View docs
              </button>
            </div>
          </div>

          <div className="grid gap-3 sm:grid-cols-3">
            {[
              ['Revenue', '$128K', '+12.4%'],
              ['Active users', '24,890', '+8.1%'],
              ['Deploys', '42', 'Today'],
            ].map(([label, value, trend]) => (
              <div key={label} className="rounded-lg border border-neutral-200 p-4">
                <p className="text-xs text-neutral-500">{label}</p>
                <p className="mt-2 text-2xl font-semibold">{value}</p>
                <p className="mt-1 text-xs text-emerald-600">{trend}</p>
              </div>
            ))}
          </div>
        </section>

        <aside className="space-y-3">
          <div className="rounded-lg border border-neutral-200 bg-[#fafafa] p-4">
            <div className="flex items-center justify-between">
              <p className="text-sm font-medium">Build graph</p>
              <Database className="h-4 w-4 text-neutral-500" />
            </div>
            <div className="mt-4 space-y-2">
              {['Web', 'Plan', 'DB', 'API', 'Deploy', 'LLM'].map((item, index) => (
                <div key={item} className="flex items-center gap-3 rounded-md bg-white p-2 text-sm">
                  <span className="flex h-6 w-6 items-center justify-center rounded-md bg-neutral-950 text-xs text-white">
                    {index + 1}
                  </span>
                  {item}
                </div>
              ))}
            </div>
          </div>

          {designMode ? (
            <div className="rounded-lg border border-orange-200 bg-orange-50 p-4">
              <div className="flex items-center gap-2">
                <Wand2 className="h-4 w-4 text-orange-700" />
                <p className="text-sm font-medium text-orange-950">Design Mode is editing this preview</p>
              </div>
              <div className="mt-3 grid grid-cols-3 gap-2">
                {['Colors', 'Type', 'Spacing'].map((item) => (
                  <button key={item} className="h-8 rounded-md bg-white text-xs text-orange-950 shadow-sm">
                    {item}
                  </button>
                ))}
              </div>
            </div>
          ) : null}

          <img
            src={templateImages[selectedTemplate.image]}
            alt=""
            className="aspect-[16/10] w-full rounded-lg border border-neutral-200 object-cover"
          />
        </aside>
      </div>
    </div>
  )
}

function CodePanel({
  files,
  selectedFilePath,
  code,
  fileName,
  copied,
  onCopy,
  onDownload,
  onSelectFile,
}: {
  files: SnapshotFile[]
  selectedFilePath: string | null
  code: string
  fileName: string
  copied: boolean
  onCopy: () => void
  onDownload: () => void
  onSelectFile: (filePath: string) => void
}) {
  return (
    <div className="mx-auto max-w-5xl overflow-hidden rounded-lg border border-neutral-800 bg-neutral-950 text-white shadow-sm">
      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-white/10 px-4 py-3">
        <div className="flex items-center gap-2 text-sm">
          <FileCode2 className="h-4 w-4 text-neutral-400" />
          {fileName}
        </div>
        <div className="flex gap-2">
          <button className="inline-flex h-8 items-center gap-2 rounded-md bg-white/10 px-3 text-sm hover:bg-white/15" onClick={onCopy}>
            <Copy className="h-4 w-4" />
            {copied ? 'Copied' : 'Copy'}
          </button>
          <button className="inline-flex h-8 items-center gap-2 rounded-md bg-white px-3 text-sm font-medium text-neutral-950" onClick={onDownload}>
            <Download className="h-4 w-4" />
            Download
          </button>
        </div>
      </div>
      <div className={files.length > 0 ? 'grid min-h-[520px] md:grid-cols-[220px_1fr]' : ''}>
        {files.length > 0 ? (
          <aside className="border-b border-white/10 bg-white/[0.03] p-2 md:border-b-0 md:border-r">
            {files.map((file) => (
              <button
                key={file.path}
                className={`flex h-9 w-full items-center gap-2 rounded-md px-2 text-left text-xs ${
                  selectedFilePath === file.path
                    ? 'bg-white text-neutral-950'
                    : 'text-neutral-300 hover:bg-white/10 hover:text-white'
                }`}
                onClick={() => onSelectFile(file.path)}
              >
                <FileCode2 className="h-3.5 w-3.5 shrink-0" />
                <span className="truncate">{file.path}</span>
              </button>
            ))}
          </aside>
        ) : null}
        <pre className="overflow-x-auto p-5 text-sm leading-6 text-neutral-200">
          <code>{code}</code>
        </pre>
      </div>
    </div>
  )
}

function DesignPanel({ enabled, onToggle }: { enabled: boolean; onToggle: () => void }) {
  return (
    <div className="mx-auto grid max-w-5xl gap-4 lg:grid-cols-[0.8fr_1.2fr]">
      <section className="rounded-lg border border-neutral-200 bg-white p-4">
        <div className="flex items-center justify-between">
          <div>
            <p className="text-sm font-medium">Design system</p>
            <p className="text-xs text-neutral-500">Tune reusable project tokens.</p>
          </div>
          <button
            className={`h-7 w-12 rounded-full p-1 transition ${enabled ? 'bg-neutral-950' : 'bg-neutral-200'}`}
            onClick={onToggle}
            aria-label="Toggle design mode"
          >
            <span className={`block h-5 w-5 rounded-full bg-white transition ${enabled ? 'translate-x-5' : ''}`} />
          </button>
        </div>

        <div className="mt-5 space-y-5">
          <TokenSlider label="Radius" value="8px" width="70%" />
          <TokenSlider label="Density" value="Comfortable" width="48%" />
          <TokenSlider label="Contrast" value="AA" width="82%" />
        </div>
      </section>

      <section className="rounded-lg border border-neutral-200 bg-white p-4">
        <p className="text-sm font-medium">Theme palette</p>
        <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">
          {[
            ['Neutral', 'bg-neutral-950'],
            ['Canvas', 'bg-[#fafafa]'],
            ['Accent', 'bg-orange-500'],
            ['Success', 'bg-emerald-500'],
          ].map(([label, color]) => (
            <button key={label} className="rounded-lg border border-neutral-200 p-2 text-left hover:bg-neutral-50">
              <span className={`block h-16 rounded-md ${color}`} />
              <span className="mt-2 block text-sm">{label}</span>
            </button>
          ))}
        </div>

        <div className="mt-5 rounded-lg border border-neutral-200 bg-[#fafafa] p-4">
          <p className="text-sm font-medium">Component states</p>
          <div className="mt-3 flex flex-wrap gap-2">
            {['Default', 'Hover', 'Focused', 'Disabled'].map((state) => (
              <button key={state} className="h-8 rounded-md border border-neutral-200 bg-white px-3 text-sm">
                {state}
              </button>
            ))}
          </div>
        </div>
      </section>
    </div>
  )
}

function TokenSlider({ label, value, width }: { label: string; value: string; width: string }) {
  return (
    <div>
      <div className="mb-2 flex justify-between text-sm">
        <span>{label}</span>
        <span className="text-neutral-500">{value}</span>
      </div>
      <div className="h-2 rounded-full bg-neutral-100">
        <div className="h-full rounded-full bg-neutral-950" style={{ width }} />
      </div>
    </div>
  )
}

function DeployPanel({ open, onToggle }: { open: boolean; onToggle: () => void }) {
  return (
    <div className="mx-auto max-w-5xl rounded-lg border border-neutral-200 bg-white p-5 shadow-sm">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <p className="text-sm font-medium text-neutral-500">Production</p>
          <h2 className="mt-1 text-2xl font-semibold">Deploy to Vercel</h2>
          <p className="mt-2 max-w-2xl text-sm leading-6 text-neutral-600">
            Go live instantly, open a pull request, or push generated code to a repository.
          </p>
        </div>
        <button
          className="inline-flex h-9 min-w-[156px] items-center justify-center gap-2 whitespace-nowrap rounded-md bg-neutral-950 px-4 text-sm font-medium text-white hover:bg-neutral-800"
          onClick={onToggle}
        >
          {open ? <CheckCircle2 className="h-4 w-4" /> : <UploadCloud className="h-4 w-4" />}
          {open ? 'Deployment queued' : 'Deploy to Vercel'}
        </button>
      </div>

      <div className="mt-6 grid gap-3 md:grid-cols-3">
        {[
          ['Preview URL', 'v0-clone.vercel.app', ExternalLink],
          ['Repository', 'github.com/team/v0-clone', Github],
          ['Diagnostics', 'No blocking errors', CheckCircle2],
        ].map(([label, value, Icon]) => (
          <div key={label as string} className="rounded-lg border border-neutral-200 bg-[#fafafa] p-4">
            <Icon className="h-5 w-5 text-neutral-500" />
            <p className="mt-4 text-xs text-neutral-500">{label as string}</p>
            <p className="mt-1 truncate text-sm font-medium">{value as string}</p>
          </div>
        ))}
      </div>

      {open ? (
        <div className="mt-5 rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-950">
          Build output is ready. The mocked deployment flow now shows the same success state a v0 user expects before publishing.
        </div>
      ) : null}

      <div className="mt-5 rounded-lg border border-neutral-200">
        {['Install dependencies', 'Run type checks', 'Create preview deployment', 'Open pull request'].map((item, index) => (
          <div key={item} className="flex items-center gap-3 border-b border-neutral-200 px-4 py-3 last:border-b-0">
            <span className="flex h-6 w-6 items-center justify-center rounded-full bg-neutral-950 text-xs text-white">
              {index + 1}
            </span>
            <span className="text-sm">{item}</span>
            <CheckCircle2 className="ml-auto h-4 w-4 text-emerald-600" />
          </div>
        ))}
      </div>
    </div>
  )
}
