import {
  FormEvent,
  lazy,
  Suspense,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import {
  ArrowRight,
  CheckCircle2,
  ChevronDown,
  Code2,
  Copy,
  Download,
  ExternalLink,
  Eye,
  FileCode2,
  Gamepad2,
  Github,
  Grid2X2,
  Heart,
  Image,
  LineChart,
  Mail,
  Mic,
  Monitor,
  Palette,
  PanelLeftClose,
  PanelLeftOpen,
  RefreshCw,
  Rocket,
  Settings2,
  SlidersHorizontal,
  Sparkles,
  UploadCloud,
  Upload,
  Users,
} from 'lucide-react'
import row01 from '@/assets/v0/template-row01.png'
import row02 from '@/assets/v0/template-row02.png'
import iosLight from '@/assets/v0/ios-light.png'
import { ConversationTimeline } from '@/components/ConversationTimeline'
import { RecentChats } from '@/components/RecentChats'
import { WorkspaceEditComposer } from '@/components/WorkspaceEditComposer'
import { agentApi, authApi, chatApi, projectApi } from '@/services/api'
import { monitorAgentRun } from '@/services/agentRunMonitor'
import {
  buildChatPath,
  buildEditRunRequest,
  resolveRoutedProjectId,
} from '@/lib/chatWorkspace'
import { getSnapshotPreviewState } from '@/lib/snapshotPreview'
import {
  createChatHistoryState,
  failChatHistory,
  loadChatHistory,
  type ChatHistoryState,
} from '@/lib/chatHistory'
import {
  applyTimelineEvent,
  createTimelineState,
  failTimelineLoading,
  insertTimelineRun,
  mergeOlderTimelinePage,
  replaceTimelinePage,
  resetTimeline,
  startTimelineLoading,
  toggleTimelineTurn,
  type ChatTimelineState,
} from '@/lib/chatTimeline'
import {
  applyAgentEvent,
  applyAgentRunDetail,
  applyRunHistory,
  applySnapshotList,
  applyWorkspaceSnapshot,
  createInitialWorkspaceState,
  failApiGeneration,
  isCancellableRunId,
  resetWorkspaceForChat,
  selectTemplate,
  startApiGeneration,
  switchPanel,
  suggestionPrompts,
  templates,
  type Panel,
  type SnapshotFile,
  type Template,
  type WorkspaceState,
} from '@/lib/v0Workspace'

const templateImages: Record<Template['image'], string> = {
  row01,
  row02,
  ios: iosLight,
}

const SnapshotPreview = lazy(async () => {
  const module = await import('@/components/SnapshotPreview')
  return { default: module.SnapshotPreview }
})

const categoryFilters: Array<{
  id: 'all' | Template['category']
  label: string
  icon: typeof Grid2X2
}> = [
  { id: 'apps', label: 'Apps and Games', icon: Gamepad2 },
  { id: 'landing', label: 'Landing Pages', icon: Monitor },
  { id: 'components', label: 'Components', icon: Grid2X2 },
  { id: 'dashboard', label: 'Dashboards', icon: LineChart },
]

const panelTabs: Array<{
  id: Panel
  label: string
  icon: typeof Eye
}> = [
  { id: 'preview', label: 'Preview', icon: Eye },
  { id: 'code', label: 'Code', icon: Code2 },
  { id: 'design', label: 'Design', icon: SlidersHorizontal },
  { id: 'deploy', label: 'Deploy', icon: Rocket },
]

const promptIcons = {
  'Contact Form': Mail,
  'Image Editor': Image,
  'Mini Game': Gamepad2,
  'Finance Calculator': LineChart,
}

const sampleCode = `import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export default function GeneratedApp() {
  return (
    <main className="min-h-screen bg-white text-neutral-950">
      <section className="mx-auto grid max-w-6xl gap-6 px-6 py-10 lg:grid-cols-[1.2fr_0.8fr]">
        <Card className="rounded-lg border-neutral-200">
          <CardContent className="space-y-4 p-6">
            <p className="text-sm text-neutral-500">Generated by v0</p>
            <h1 className="text-3xl font-semibold">Production-ready interface</h1>
            <Button>Publish to Vercel</Button>
          </CardContent>
        </Card>
      </section>
    </main>
  )
}`

const getErrorMessage = (error: unknown) => {
  const apiError = error as {
    response?: { data?: { error?: string; message?: string } }
    message?: string
  }

  return apiError.response?.data?.error ?? apiError.response?.data?.message ?? apiError.message ?? 'Agent request failed'
}

const isAbortError = (error: unknown): boolean =>
  error instanceof Error && error.name === 'AbortError'

const createDemoProject = async (prompt: string) => {
  if (!localStorage.getItem('token')) {
    const unique = `${Date.now()}-${Math.random().toString(16).slice(2)}`
    const authResponse = await authApi.register(
      `phase5-${unique}@v0.local`,
      'password123',
      'Phase Five Demo',
    )
    localStorage.setItem('token', authResponse.data.token)
  }

  const projectResponse = await projectApi.create({
    name: `v0 Snapshot ${new Date().toLocaleTimeString()}`,
    description: prompt,
    settings: {
      framework: 'react',
      styling: 'tailwind',
      uiLibrary: 'shadcn',
    },
  })

  return projectResponse.data.project._id as string
}

export function V0Clone() {
  const navigate = useNavigate()
  const { chatId } = useParams<{ chatId: string }>()
  const [workspace, setWorkspace] = useState(createInitialWorkspaceState)
  const [draftPrompt, setDraftPrompt] = useState('')
  const [editDraft, setEditDraft] = useState('')
  const [submissionPending, setSubmissionPending] = useState(false)
  const [routeError, setRouteError] = useState<string>()
  const [modelOpen, setModelOpen] = useState(false)
  const [model, setModel] = useState('Mock provider')
  const [category, setCategory] = useState<'all' | Template['category']>('all')
  const [designMode, setDesignMode] = useState(true)
  const [deployOpen, setDeployOpen] = useState(false)
  const [copied, setCopied] = useState(false)
  const [workspaceSidebarCollapsed, setWorkspaceSidebarCollapsed] = useState(false)
  const [timeline, setTimeline] = useState(createTimelineState)
  const [chatHistory, setChatHistory] = useState(createChatHistoryState)
  const [projectId, setProjectId] = useState('')
  const [retryingValidationRunId, setRetryingValidationRunId] = useState<string>()
  const refreshRequestRef = useRef(0)
  const routeRequestRef = useRef(0)
  const pendingNavigationChatRef = useRef<string | null>(null)
  const monitorControllerRef = useRef<AbortController | null>(null)
  const submissionInFlightRef = useRef(false)
  const submissionIdRef = useRef(0)
  const timelineRequestRef = useRef(0)
  const chatHistoryRequestRef = useRef(0)

  const visibleTemplates = useMemo(
    () => templates.filter((template) => category === 'all' || template.category === category),
    [category],
  )

  const selectedTemplate = useMemo(
    () => templates.find((template) => template.id === workspace.selectedTemplateId) ?? templates[0],
    [workspace.selectedTemplateId],
  )

  const currentPrompt = workspace.prompt || draftPrompt || selectedTemplate.prompt
  const selectedSnapshotFile = workspace.snapshot?.files.find(
    (file) => file.path === workspace.snapshot?.selectedFilePath,
  ) ?? workspace.snapshot?.files[0]
  const currentCode = selectedSnapshotFile?.content ?? sampleCode
  const currentFileName = selectedSnapshotFile?.path ?? 'generated-app.tsx'

  const refreshProjectData = async (id: string) => {
    const requestId = ++refreshRequestRef.current
    const [runsResponse, snapshotsResponse] = await Promise.all([
      agentApi.getRuns(id),
      projectApi.getSnapshots(id),
    ])
    if (requestId !== refreshRequestRef.current) {
      return null
    }
    setWorkspace((state) =>
      applySnapshotList(
        applyRunHistory(state, runsResponse.data.runs),
        snapshotsResponse.data.snapshots,
      ),
    )
    return snapshotsResponse.data.snapshots
  }

  const loadTimeline = async (
    targetChatId: string,
    before?: string,
  ): Promise<void> => {
    const requestId = ++timelineRequestRef.current
    setTimeline((state) => startTimelineLoading(state, Boolean(before)))
    try {
      const response = await chatApi.getTimeline(targetChatId, {
        limit: 20,
        ...(before ? { before } : {}),
      })
      if (requestId !== timelineRequestRef.current) return
      setTimeline((state) =>
        before
          ? mergeOlderTimelinePage(state, response.data)
          : replaceTimelinePage(state, response.data),
      )
    } catch (error) {
      if (requestId !== timelineRequestRef.current) return
      setTimeline((state) => failTimelineLoading(state, getErrorMessage(error)))
    }
  }

  const loadChatHistoryList = useCallback(async (): Promise<void> => {
    const requestId = ++chatHistoryRequestRef.current
    setChatHistory((state) => loadChatHistory(state))
    try {
      const response = await chatApi.getAll()
      if (requestId !== chatHistoryRequestRef.current) return
      setChatHistory((state) => loadChatHistory(state, response.data.chats))
    } catch {
      if (requestId !== chatHistoryRequestRef.current) return
      setChatHistory((state) =>
        failChatHistory(state, '无法加载最近聊天'),
      )
    }
  }, [])

  useEffect(() => {
    if (chatId) void loadChatHistoryList()
  }, [chatId, loadChatHistoryList])

  useEffect(() => {
    const requestId = ++routeRequestRef.current
    setRouteError(undefined)
    setEditDraft('')

    if (!chatId) {
      timelineRequestRef.current += 1
      monitorControllerRef.current?.abort()
      monitorControllerRef.current = null
      setProjectId('')
      setTimeline((state) => resetTimeline(state))
      setWorkspace(createInitialWorkspaceState())
      return
    }

    if (pendingNavigationChatRef.current === chatId) {
      pendingNavigationChatRef.current = null
      return
    }

    monitorControllerRef.current?.abort()
    monitorControllerRef.current = null
    timelineRequestRef.current += 1
    setProjectId('')
    setTimeline((state) => resetTimeline(state))
    setWorkspace((state) => resetWorkspaceForChat(state))

    void (async () => {
      try {
        const chatResponse = await chatApi.getById(chatId)
        const routedProjectId = resolveRoutedProjectId(chatResponse.data.chat)
        if (requestId !== routeRequestRef.current) return

        setProjectId(routedProjectId)
        setWorkspace((state) => ({
          ...state,
          prompt:
            [...chatResponse.data.chat.messages]
              .reverse()
              .find((message) => message.role === 'user')?.content ??
            chatResponse.data.chat.title,
        }))
        void loadTimeline(chatId)

        const snapshots = await refreshProjectData(routedProjectId)
        if (requestId !== routeRequestRef.current) return
        const activeSnapshotId = snapshots?.find((snapshot) => snapshot.isActive)?.id
        if (!activeSnapshotId) return

        const snapshotResponse = await projectApi.getSnapshot(
          routedProjectId,
          activeSnapshotId,
        )
        if (requestId !== routeRequestRef.current) return
        setWorkspace((state) =>
          applyWorkspaceSnapshot(state, snapshotResponse.data.snapshot),
        )
      } catch (error) {
        if (requestId !== routeRequestRef.current) return
        setRouteError(getErrorMessage(error))
      }
    })()
  }, [chatId])

  useEffect(() => () => {
    monitorControllerRef.current?.abort()
  }, [])

  const submitPromptToAgent = async (rawPrompt: string) => {
    const prompt = rawPrompt.trim()

    if (!prompt || workspace.generation.status === 'running' || submissionInFlightRef.current) {
      return
    }

    submissionInFlightRef.current = true
    setSubmissionPending(true)
    const submissionId = ++submissionIdRef.current
    let activeTimelineRunId: string | undefined

    if (!chatId) {
      setDraftPrompt(prompt)
    }
    setWorkspace((state) =>
      startApiGeneration(state, prompt, `pending:${crypto.randomUUID()}`),
    )

    try {
      let activeProjectId = projectId
      let activeChatId = chatId
      let runRequest: Parameters<typeof agentApi.createRun>[0]

      if (!activeChatId) {
        activeProjectId = await createDemoProject(prompt)
        const chatResponse = await chatApi.create(prompt, activeProjectId)
        activeChatId = chatResponse.data.chat._id
        runRequest = {
          projectId: activeProjectId,
          chatId: activeChatId,
          prompt,
          mode: 'create',
        }
      } else {
        runRequest = buildEditRunRequest({
          chatId: activeChatId,
          projectId: activeProjectId,
          prompt,
          activeSnapshotId: workspace.snapshot?.id,
        })
      }

      const runResponse = await agentApi.createRun(runRequest)

      if (submissionId !== submissionIdRef.current) return
      if (!chatId) {
        setProjectId(activeProjectId)
        pendingNavigationChatRef.current = activeChatId
        navigate(buildChatPath(activeChatId))
      }

      monitorControllerRef.current?.abort()
      const controller = new AbortController()
      monitorControllerRef.current = controller
      const token = localStorage.getItem('token')
      if (!token) throw new Error('Authentication token is unavailable')

      const runId = runResponse.data.run._id
      activeTimelineRunId = runId
      setTimeline((state) => insertTimelineRun(state, runResponse.data.run))
      setWorkspace((state) => startApiGeneration(state, prompt, runId))
      const detail = await monitorAgentRun({
        runId,
        token,
        signal: controller.signal,
        onEvent: (event) => {
          setWorkspace((state) => applyAgentEvent(state, runId, event))
          setTimeline((state) => applyTimelineEvent(state, runId, {
            ...event,
            createdAt: new Date().toISOString(),
          }))
        },
      })
      setWorkspace((state) => applyAgentRunDetail(state, detail))
      await refreshProjectData(activeProjectId)
      await loadTimeline(activeChatId)
      if (chatId && detail.run.status === 'completed') {
        setEditDraft((current) => current.trim() === prompt ? '' : current)
      }
    } catch (error) {
      if (!isAbortError(error) && submissionId === submissionIdRef.current) {
        setWorkspace((state) => failApiGeneration(state, getErrorMessage(error)))
        setTimeline((state) => {
          if (!activeTimelineRunId) return state
          const activeTurn = state.turns.find(
            (turn) => turn.runId === activeTimelineRunId,
          )
          if (!activeTurn) return state
          const maxSequence = Math.max(
            0,
            ...activeTurn.agent.events.map((event) => event.sequence),
          )
          return applyTimelineEvent(state, activeTimelineRunId, {
            type: 'run.failed',
            sequence: maxSequence + 1,
            message: getErrorMessage(error),
            createdAt: new Date().toISOString(),
          })
        })
      }
    } finally {
      if (submissionId === submissionIdRef.current) {
        submissionInFlightRef.current = false
        setSubmissionPending(false)
      }
    }
  }

  const handleCancelRun = async (requestedRunId?: string) => {
    const runId = requestedRunId ?? workspace.generation.runId
    if (!isCancellableRunId(runId)) return
    monitorControllerRef.current?.abort()
    monitorControllerRef.current = null
    try {
      const response = await agentApi.cancelRun(runId)
      setWorkspace((state) => applyAgentRunDetail(state, {
        run: response.data.run,
        events: [],
        resultSnapshot: null,
      }))
      if (projectId) await refreshProjectData(projectId)
      if (chatId) await loadTimeline(chatId)
    } catch (error) {
      setWorkspace((state) => failApiGeneration(state, getErrorMessage(error)))
    }
  }

  const handleBackHome = () => {
    submissionIdRef.current += 1
    submissionInFlightRef.current = false
    setSubmissionPending(false)
    monitorControllerRef.current?.abort()
    monitorControllerRef.current = null
    navigate('/')
  }

  const handleSelectTimelineSnapshot = async (snapshotId: string) => {
    if (!projectId) return
    const response = await projectApi.getSnapshot(projectId, snapshotId)
    setWorkspace((state) => applyWorkspaceSnapshot(state, response.data.snapshot))
  }

  const handleRetryValidation = async (failedRunId: string) => {
    if (retryingValidationRunId || !projectId || !chatId) return
    setRetryingValidationRunId(failedRunId)
    try {
      const response = await agentApi.retryValidation(failedRunId)
      const retryRunId = response.data.run._id
      setTimeline((state) => insertTimelineRun(state, response.data.run))
      const token = localStorage.getItem('token')
      if (!token) throw new Error('Authentication token is unavailable')
      const controller = new AbortController()
      await monitorAgentRun({
        runId: retryRunId,
        token,
        signal: controller.signal,
        onEvent: (event) => {
          setTimeline((state) => applyTimelineEvent(state, retryRunId, {
            ...event,
            createdAt: new Date().toISOString(),
          }))
        },
      })
      await Promise.all([
        refreshProjectData(projectId),
        loadTimeline(chatId),
      ])
    } catch {
      await loadTimeline(chatId)
    } finally {
      setRetryingValidationRunId(undefined)
    }
  }

  const handlePromptSubmit = (event?: FormEvent) => {
    event?.preventDefault()
    void submitPromptToAgent(draftPrompt || selectedTemplate.prompt)
  }

  const handleTemplateSelect = (templateId: string) => {
    const next = selectTemplate(workspace, templateId)
    setWorkspace(next)
    setDraftPrompt(next.prompt)
  }

  const handleSuggestion = (label: string) => {
    const prompt = `Build a ${label.toLowerCase()} with polished interactions, responsive states, and production-ready code.`
    setDraftPrompt(prompt)
  }

  const handleCopy = async () => {
    await navigator.clipboard.writeText(currentCode)
    setCopied(true)
    window.setTimeout(() => setCopied(false), 1600)
  }

  const handleDownload = () => {
    const blob = new Blob([currentCode], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const anchor = document.createElement('a')
    anchor.href = url
    anchor.download = currentFileName.split('/').pop() ?? 'generated-app.tsx'
    anchor.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="min-h-screen bg-[#fafafa] text-neutral-950 antialiased">
      <TopNav />

      {routeError ? (
        <main className="mx-auto flex min-h-[calc(100vh-48px)] max-w-xl items-center px-6 text-center">
          <div className="w-full rounded-lg border border-red-200 bg-red-50 p-5 text-sm text-red-950">
            <p className="font-medium">Unable to load this conversation</p>
            <p className="mt-2" data-testid="chat-route-error">{routeError}</p>
            <button
              className="mt-4 rounded-md bg-neutral-950 px-3 py-2 text-white"
              onClick={handleBackHome}
            >
              Start a new chat
            </button>
          </div>
        </main>
      ) : workspace.screen === 'home' ? (
        <main className="mx-auto w-full max-w-[1240px] px-3 pb-16 pt-20 sm:px-6 lg:pt-32">
          <section className="mx-auto flex max-w-[720px] flex-col items-center text-center">
            <h1 className="text-[28px] font-semibold leading-tight sm:text-[30px]">
              您想创建什么?
            </h1>

            <form
              className="mt-5 w-full rounded-lg border border-neutral-300 bg-white shadow-sm transition focus-within:border-neutral-500 focus-within:shadow-md"
              onSubmit={handlePromptSubmit}
            >
              <textarea
                value={draftPrompt}
                onChange={(event) => setDraftPrompt(event.target.value)}
                onKeyDown={(event) => {
                  if (event.key === 'Enter' && !event.shiftKey) {
                    event.preventDefault()
                    void submitPromptToAgent(draftPrompt || selectedTemplate.prompt)
                  }
                }}
                placeholder="让 v0 构建..."
                className="h-20 w-full resize-none rounded-t-lg bg-transparent px-4 py-4 text-sm leading-6 text-neutral-800 outline-none placeholder:text-neutral-400 sm:h-[74px]"
              />
              <div className="flex items-center justify-between px-3 pb-3">
                <div className="relative">
                  <button
                    type="button"
                    className="inline-flex h-8 items-center gap-2 rounded-md px-2 text-sm text-neutral-600 hover:bg-neutral-100"
                    onClick={() => setModelOpen((open) => !open)}
                  >
                    <Sparkles className="h-4 w-4 text-orange-500" />
                    {model}
                    <ChevronDown className="h-3.5 w-3.5" />
                  </button>
                  {modelOpen ? (
                    <div className="absolute left-0 top-10 z-20 w-44 rounded-lg border border-neutral-200 bg-white p-1 text-left text-sm shadow-xl">
                      {['Mock provider', 'Fable 5', 'Opus 4.5', 'Fast Build'].map((item) => (
                        <button
                          type="button"
                          key={item}
                          className="flex w-full items-center justify-between rounded-md px-3 py-2 text-neutral-700 hover:bg-neutral-100"
                          onClick={() => {
                            setModel(item)
                            setModelOpen(false)
                          }}
                        >
                          {item}
                          {model === item ? <CheckCircle2 className="h-4 w-4" /> : null}
                        </button>
                      ))}
                    </div>
                  ) : null}
                </div>

                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    className="hidden h-8 w-8 items-center justify-center rounded-md text-neutral-500 hover:bg-neutral-100 sm:inline-flex"
                    aria-label="Upload context"
                  >
                    <Upload className="h-4 w-4" />
                  </button>
                  <button
                    type="button"
                    className="h-8 w-8 rounded-md bg-neutral-950 text-white hover:bg-neutral-800"
                    aria-label="Voice prompt"
                  >
                    <Mic className="mx-auto h-4 w-4" />
                  </button>
                  {draftPrompt.trim() ? (
                    <button
                      type="submit"
                      className="inline-flex h-8 w-8 items-center justify-center rounded-md bg-neutral-950 text-white hover:bg-neutral-800 disabled:cursor-not-allowed disabled:bg-neutral-400"
                      aria-label="Build prompt"
                      disabled={workspace.generation.status === 'running'}
                    >
                      {workspace.generation.status === 'running' ? <RefreshCw className="h-4 w-4 animate-spin" /> : <ArrowRight className="h-4 w-4" />}
                    </button>
                  ) : null}
                </div>
              </div>
            </form>

            <div className="mt-4 flex flex-wrap justify-center gap-2">
              {suggestionPrompts.map((label) => {
                const Icon = promptIcons[label]
                return (
                  <button
                    key={label}
                    className="inline-flex h-8 items-center gap-2 rounded-full border border-neutral-200 bg-white px-3 text-sm text-neutral-600 shadow-sm hover:border-neutral-300 hover:bg-neutral-50"
                    onClick={() => handleSuggestion(label)}
                  >
                    <Icon className="h-4 w-4" />
                    {label}
                  </button>
                )
              })}
              <button
                className="inline-flex h-8 w-8 items-center justify-center rounded-full border border-neutral-200 bg-white text-neutral-600 shadow-sm hover:border-neutral-300 hover:bg-neutral-50"
                aria-label="Refresh suggestions"
                onClick={() => setDraftPrompt('Create a clean AI analytics workspace with charts, files, and deploy controls.')}
              >
                <RefreshCw className="h-4 w-4" />
              </button>
            </div>
          </section>

          <section className="mt-24 sm:mt-32">
            <div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between">
              <h2 className="text-2xl font-semibold">Start with a template</h2>
              <div className="hidden flex-wrap items-center gap-2 sm:flex">
                {categoryFilters.map((filter) => {
                  const Icon = filter.icon
                  const active = category === filter.id
                  return (
                    <button
                      key={filter.id}
                      className={`inline-flex h-8 items-center gap-2 rounded-full border px-3 text-sm ${
                        active
                          ? 'border-neutral-950 bg-neutral-950 text-white'
                          : 'border-neutral-200 bg-white text-neutral-600 hover:bg-neutral-50'
                      }`}
                      onClick={() => setCategory(active ? 'all' : filter.id)}
                    >
                      <Icon className="h-4 w-4" />
                      {filter.label}
                    </button>
                  )
                })}
                <button
                  className="inline-flex h-8 items-center gap-2 rounded-full px-3 text-sm font-medium text-neutral-800 hover:bg-neutral-100"
                  onClick={() => setCategory('all')}
                >
                  Browse all
                  <ArrowRight className="h-4 w-4" />
                </button>
              </div>
            </div>

            <div className="mt-6 grid gap-7 md:grid-cols-2 lg:grid-cols-3">
              {visibleTemplates.map((template) => (
                <TemplateCard
                  key={template.id}
                  template={template}
                  imageSrc={templateImages[template.image]}
                  selected={workspace.selectedTemplateId === template.id}
                  onSelect={() => handleTemplateSelect(template.id)}
                  onBuild={() => {
                    const next = selectTemplate(workspace, template.id)
                    setWorkspace(next)
                    setDraftPrompt(next.prompt)
                    void submitPromptToAgent(next.prompt)
                  }}
                />
              ))}
            </div>
          </section>
        </main>
      ) : (
        <WorkspaceScreen
          prompt={currentPrompt}
          selectedTemplate={selectedTemplate}
          state={workspace}
          designMode={designMode}
          deployOpen={deployOpen}
          copied={copied}
          onBackHome={handleBackHome}
          onSwitchPanel={(panel) => setWorkspace((state) => switchPanel(state, panel))}
          onSelectSnapshotFile={(filePath) =>
            setWorkspace((state) =>
              state.snapshot
                ? {
                    ...state,
                    snapshot: {
                      ...state.snapshot,
                      selectedFilePath: filePath,
                    },
                  }
                : state,
            )
          }
          onToggleDesignMode={() => setDesignMode((enabled) => !enabled)}
          onToggleDeploy={() => setDeployOpen((open) => !open)}
          onCopy={handleCopy}
          onDownload={handleDownload}
          onCancelRun={() => void handleCancelRun()}
          currentCode={currentCode}
          currentFileName={currentFileName}
          editDraft={editDraft}
          submissionPending={submissionPending}
          onEditDraftChange={setEditDraft}
          onSubmitEdit={() => void submitPromptToAgent(editDraft)}
          timeline={timeline}
          onToggleTimelineTurn={(runId) =>
            setTimeline((state) => toggleTimelineTurn(state, runId))
          }
          onLoadOlderTimeline={() => {
            if (chatId && timeline.pageInfo.nextBefore) {
              void loadTimeline(chatId, timeline.pageInfo.nextBefore)
            }
          }}
          onRetryTimeline={() => {
            if (chatId) void loadTimeline(chatId)
          }}
          onSelectTimelineSnapshot={(snapshotId) =>
            void handleSelectTimelineSnapshot(snapshotId)
          }
          retryingValidationRunId={retryingValidationRunId}
          onRetryValidation={(runId) => void handleRetryValidation(runId)}
          sidebarCollapsed={workspaceSidebarCollapsed}
          onCollapseSidebar={() => setWorkspaceSidebarCollapsed(true)}
          onExpandSidebar={() => setWorkspaceSidebarCollapsed(false)}
          chatHistory={chatHistory}
          activeChatId={chatId}
          onRetryChatHistory={() => void loadChatHistoryList()}
        />
      )}
    </div>
  )
}

function TopNav() {
  return (
    <header className="sticky top-0 z-30 border-b border-neutral-200 bg-[#fafafa]/95 backdrop-blur">
      <div className="mx-auto flex h-12 max-w-[1440px] items-center justify-between px-3 sm:px-4">
        <button className="flex h-8 items-center gap-2 rounded-md text-left" aria-label="v0 home">
          <span className="text-[21px] font-black leading-none tracking-normal">v0</span>
        </button>

        <div className="hidden items-center gap-2 md:flex">
          <button className="h-8 rounded-md border border-neutral-200 bg-white px-3 text-sm hover:bg-neutral-50">
            登录
          </button>
          <button className="h-8 rounded-md bg-neutral-950 px-3 text-sm font-medium text-white hover:bg-neutral-800">
            注册
          </button>
        </div>

      </div>
    </header>
  )
}

function TemplateCard({
  template,
  imageSrc,
  selected,
  onSelect,
  onBuild,
}: {
  template: Template
  imageSrc: string
  selected: boolean
  onSelect: () => void
  onBuild: () => void
}) {
  return (
    <article className="group">
      <button
        className={`block w-full overflow-hidden rounded-lg border text-left transition ${
          selected
            ? 'border-neutral-950 ring-2 ring-neutral-950/10'
            : 'border-neutral-200 hover:border-neutral-300'
        }`}
        onClick={onSelect}
      >
        <div className="aspect-[16/9] bg-neutral-100">
          <img
            src={imageSrc}
            alt=""
            className="h-full w-full object-cover transition duration-300 group-hover:scale-[1.02]"
          />
        </div>
      </button>
      <div className="mt-2 flex items-start gap-3">
        <div className="h-9 w-9 shrink-0 rounded-full border border-neutral-200 bg-neutral-100" />
        <div className="min-w-0 flex-1">
          <h3 className="truncate text-sm font-medium">{template.title}</h3>
          <div className="mt-1 flex items-center gap-3 text-xs text-neutral-500">
            <span className="inline-flex items-center gap-1">
              <Users className="h-3.5 w-3.5" />
              {template.views}
            </span>
            <span className="inline-flex items-center gap-1">
              <Heart className="h-3.5 w-3.5" />
              {template.likes}
            </span>
          </div>
        </div>
        <button
          className="h-8 rounded-md bg-neutral-950 px-3 text-xs font-medium text-white opacity-0 transition hover:bg-neutral-800 group-hover:opacity-100"
          onClick={onBuild}
        >
          Use template
        </button>
      </div>
    </article>
  )
}

function WorkspaceScreen({
  prompt,
  selectedTemplate,
  state,
  designMode,
  deployOpen,
  copied,
  onBackHome,
  onSwitchPanel,
  onSelectSnapshotFile,
  onToggleDesignMode,
  onToggleDeploy,
  onCopy,
  onDownload,
  onCancelRun,
  currentCode,
  currentFileName,
  editDraft,
  submissionPending,
  onEditDraftChange,
  onSubmitEdit,
  timeline,
  onToggleTimelineTurn,
  onLoadOlderTimeline,
  onRetryTimeline,
  onSelectTimelineSnapshot,
  retryingValidationRunId,
  onRetryValidation,
  sidebarCollapsed,
  onCollapseSidebar,
  onExpandSidebar,
  chatHistory,
  activeChatId,
  onRetryChatHistory,
}: {
  prompt: string
  selectedTemplate: Template
  state: ReturnType<typeof createInitialWorkspaceState>
  designMode: boolean
  deployOpen: boolean
  copied: boolean
  onBackHome: () => void
  onSwitchPanel: (panel: Panel) => void
  onSelectSnapshotFile: (filePath: string) => void
  onToggleDesignMode: () => void
  onToggleDeploy: () => void
  onCopy: () => void
  onDownload: () => void
  onCancelRun: () => void
  currentCode: string
  currentFileName: string
  editDraft: string
  submissionPending: boolean
  onEditDraftChange: (value: string) => void
  onSubmitEdit: () => void
  timeline: ChatTimelineState
  onToggleTimelineTurn: (runId: string) => void
  onLoadOlderTimeline: () => void
  onRetryTimeline: () => void
  onSelectTimelineSnapshot: (snapshotId: string) => void
  retryingValidationRunId?: string
  onRetryValidation: (runId: string) => void
  sidebarCollapsed: boolean
  onCollapseSidebar: () => void
  onExpandSidebar: () => void
  chatHistory: ChatHistoryState
  activeChatId?: string
  onRetryChatHistory: () => void
}) {
  return (
    <main
      className={`grid h-[calc(100vh-48px)] min-h-0 grid-cols-1 overflow-hidden bg-white ${
        sidebarCollapsed ? 'lg:grid-cols-1' : 'lg:grid-cols-[272px_1fr]'
      }`}
    >
      {!sidebarCollapsed ? (
        <aside
          className="hidden border-r border-neutral-200 bg-[#fafafa] lg:flex lg:flex-col"
          data-testid="workspace-sidebar"
        >
          <div className="flex items-center gap-2 p-3">
            <button
              className="flex h-9 flex-1 items-center justify-center gap-2 rounded-md bg-neutral-950 text-sm font-medium text-white hover:bg-neutral-800"
              onClick={onBackHome}
            >
              <Sparkles className="h-4 w-4" />
              New chat
            </button>
            <button
              className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md border border-neutral-200 bg-white text-neutral-600 hover:bg-neutral-100"
              aria-label="Collapse sidebar"
              onClick={onCollapseSidebar}
            >
              <PanelLeftClose className="h-4 w-4" />
            </button>
          </div>
          <RecentChats
            state={chatHistory}
            activeChatId={activeChatId}
            onRetry={onRetryChatHistory}
          />
          <div className="flex-1" />
          <div className="space-y-1 border-t border-neutral-200 p-2">
            <button className="flex h-9 w-full items-center gap-2 rounded-md px-2 text-sm text-neutral-600 hover:bg-neutral-100">
              <Github className="h-4 w-4" />
              Sync with repo
            </button>
            <button className="flex h-9 w-full items-center gap-2 rounded-md px-2 text-sm text-neutral-600 hover:bg-neutral-100">
              <Settings2 className="h-4 w-4" />
              Settings
            </button>
          </div>
        </aside>
      ) : (
        <button
          className="fixed left-2 top-14 z-40 hidden h-9 w-9 items-center justify-center rounded-md border border-neutral-200 bg-white text-neutral-600 shadow-md hover:bg-neutral-50 lg:inline-flex"
          aria-label="Expand sidebar"
          onClick={onExpandSidebar}
        >
          <PanelLeftOpen className="h-4 w-4" />
        </button>
      )}

      <section className="flex min-h-0 min-w-0 flex-col">
        <div className="flex h-13 min-h-13 items-center justify-between border-b border-neutral-200 px-3 py-2 sm:px-4">
          <div className="min-w-0">
            <p className="truncate text-sm font-medium">{selectedTemplate.title}</p>
            <p className="truncate text-xs text-neutral-500">{prompt}</p>
          </div>
          <div className="flex items-center gap-2">
            <button className="hidden h-8 items-center gap-2 rounded-md border border-neutral-200 px-3 text-sm text-neutral-700 hover:bg-neutral-50 sm:inline-flex">
              <Github className="h-4 w-4" />
              Sync
            </button>
            <button
              className="h-8 rounded-md bg-neutral-950 px-3 text-sm font-medium text-white hover:bg-neutral-800"
              onClick={onToggleDeploy}
            >
              Publish
            </button>
          </div>
        </div>

        <div className="grid min-h-0 flex-1 grid-cols-1 grid-rows-[minmax(0,1fr)_minmax(0,1fr)] overflow-hidden xl:grid-cols-[440px_1fr] xl:grid-rows-1">
          <section className="flex min-h-0 flex-col border-b border-neutral-200 xl:border-b-0 xl:border-r">
            <div
              className="sr-only"
              data-testid="agent-generation-status"
              data-status={state.generation.status}
            >
              {state.generation.status}
            </div>
            <ConversationTimeline
              state={timeline}
              activeRunId={
                isCancellableRunId(state.generation.runId)
                  ? state.generation.runId
                  : undefined
              }
              onToggleTurn={onToggleTimelineTurn}
              onLoadOlder={onLoadOlderTimeline}
              onRetry={onRetryTimeline}
              onSelectSnapshot={onSelectTimelineSnapshot}
              onCancelRun={onCancelRun}
              retryingRunId={retryingValidationRunId}
              onRetryValidation={onRetryValidation}
            />
            <WorkspaceEditComposer
              value={editDraft}
              disabled={state.generation.status === 'running' || submissionPending}
              canSubmit={Boolean(state.snapshot) && Boolean(editDraft.trim())}
              onChange={onEditDraftChange}
              onSubmit={onSubmitEdit}
            />
          </section>

          <section className="flex min-w-0 flex-col bg-[#f5f5f5]">
            <div className="flex flex-wrap items-center justify-between gap-3 border-b border-neutral-200 bg-white px-3 py-2">
              <div className="flex rounded-md border border-neutral-200 bg-neutral-100 p-0.5">
                {panelTabs.map((tab) => {
                  const Icon = tab.icon
                  const active = state.activePanel === tab.id
                  return (
                    <button
                      key={tab.id}
                      className={`inline-flex h-8 items-center gap-2 rounded px-3 text-sm ${
                        active ? 'bg-white text-neutral-950 shadow-sm' : 'text-neutral-600 hover:text-neutral-950'
                      }`}
                      onClick={() => onSwitchPanel(tab.id)}
                    >
                      <Icon className="h-4 w-4" />
                      {tab.label}
                    </button>
                  )
                })}
              </div>
              <div className="flex items-center gap-2">
                <button
                  className={`inline-flex h-8 items-center gap-2 rounded-md border px-3 text-sm ${
                    designMode ? 'border-neutral-950 bg-neutral-950 text-white' : 'border-neutral-200 bg-white text-neutral-700'
                  }`}
                  onClick={onToggleDesignMode}
                >
                  <Palette className="h-4 w-4" />
                  Design Mode
                </button>
                <button
                  className="inline-flex h-8 items-center gap-2 rounded-md border border-neutral-200 bg-white px-3 text-sm text-neutral-700 hover:bg-neutral-50"
                  onClick={onCopy}
                >
                  <Copy className="h-4 w-4" />
                  {copied ? 'Copied' : 'Copy'}
                </button>
              </div>
            </div>

            <div className="flex-1 overflow-y-auto p-3 sm:p-5">
              {state.activePanel === 'preview' ? (
                <PreviewPanel
                  snapshot={state.snapshot}
                  generationStatus={state.generation.status}
                />
              ) : null}
              {state.activePanel === 'code' ? (
                <CodePanel
                  files={state.snapshot?.files ?? []}
                  selectedFilePath={state.snapshot?.selectedFilePath ?? null}
                  code={currentCode}
                  fileName={currentFileName}
                  copied={copied}
                  onCopy={onCopy}
                  onDownload={onDownload}
                  onSelectFile={onSelectSnapshotFile}
                />
              ) : null}
              {state.activePanel === 'design' ? <DesignPanel enabled={designMode} onToggle={onToggleDesignMode} /> : null}
              {state.activePanel === 'deploy' ? <DeployPanel open={deployOpen} onToggle={onToggleDeploy} /> : null}
            </div>
          </section>
        </div>
      </section>
    </main>
  )
}

function PreviewPanel({
  snapshot,
  generationStatus,
}: {
  snapshot: WorkspaceState['snapshot']
  generationStatus: WorkspaceState['generation']['status']
}) {
  const previewState = getSnapshotPreviewState(snapshot, generationStatus)

  if (previewState.kind === 'empty') {
    return (
      <div className="mx-auto flex min-h-[420px] max-w-5xl items-center justify-center rounded-lg border border-dashed border-neutral-300 bg-white p-8 text-center">
        <div>
          <Eye className="mx-auto h-8 w-8 text-neutral-400" />
          <h2 className="mt-4 text-base font-semibold">Preview is waiting for a snapshot</h2>
          <p className="mt-2 max-w-md text-sm leading-6 text-neutral-500">
            Submit a prompt and the successfully generated React application will run here.
          </p>
        </div>
      </div>
    )
  }

  if (previewState.kind === 'error') {
    return (
      <div className="mx-auto max-w-5xl rounded-lg border border-red-200 bg-red-50 p-5 text-sm text-red-950">
        <p className="font-medium">Preview is unavailable</p>
        <p className="mt-2">{previewState.message}</p>
      </div>
    )
  }

  return (
    <div className="mx-auto max-w-5xl">
      <Suspense
        fallback={(
          <div className="flex min-h-[620px] items-center justify-center rounded-lg border border-neutral-200 bg-white text-sm text-neutral-500">
            Loading isolated preview…
          </div>
        )}
      >
        <SnapshotPreview
          snapshotId={snapshot!.id}
          model={previewState.model}
          isGenerating={previewState.kind === 'running'}
        />
      </Suspense>
    </div>
  )
}

function CodePanel({
  files,
  selectedFilePath,
  code,
  fileName,
  copied,
  onCopy,
  onDownload,
  onSelectFile,
}: {
  files: SnapshotFile[]
  selectedFilePath: string | null
  code: string
  fileName: string
  copied: boolean
  onCopy: () => void
  onDownload: () => void
  onSelectFile: (filePath: string) => void
}) {
  return (
    <div className="mx-auto max-w-5xl overflow-hidden rounded-lg border border-neutral-800 bg-neutral-950 text-white shadow-sm">
      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-white/10 px-4 py-3">
        <div className="flex items-center gap-2 text-sm">
          <FileCode2 className="h-4 w-4 text-neutral-400" />
          {fileName}
        </div>
        <div className="flex gap-2">
          <button className="inline-flex h-8 items-center gap-2 rounded-md bg-white/10 px-3 text-sm hover:bg-white/15" onClick={onCopy}>
            <Copy className="h-4 w-4" />
            {copied ? 'Copied' : 'Copy'}
          </button>
          <button className="inline-flex h-8 items-center gap-2 rounded-md bg-white px-3 text-sm font-medium text-neutral-950" onClick={onDownload}>
            <Download className="h-4 w-4" />
            Download
          </button>
        </div>
      </div>
      <div className={files.length > 0 ? 'grid min-h-[520px] md:grid-cols-[220px_1fr]' : ''}>
        {files.length > 0 ? (
          <aside className="border-b border-white/10 bg-white/[0.03] p-2 md:border-b-0 md:border-r">
            {files.map((file) => (
              <button
                key={file.path}
                className={`flex h-9 w-full items-center gap-2 rounded-md px-2 text-left text-xs ${
                  selectedFilePath === file.path
                    ? 'bg-white text-neutral-950'
                    : 'text-neutral-300 hover:bg-white/10 hover:text-white'
                }`}
                onClick={() => onSelectFile(file.path)}
              >
                <FileCode2 className="h-3.5 w-3.5 shrink-0" />
                <span className="truncate">{file.path}</span>
              </button>
            ))}
          </aside>
        ) : null}
        <pre className="overflow-x-auto p-5 text-sm leading-6 text-neutral-200">
          <code>{code}</code>
        </pre>
      </div>
    </div>
  )
}

function DesignPanel({ enabled, onToggle }: { enabled: boolean; onToggle: () => void }) {
  return (
    <div className="mx-auto grid max-w-5xl gap-4 lg:grid-cols-[0.8fr_1.2fr]">
      <section className="rounded-lg border border-neutral-200 bg-white p-4">
        <div className="flex items-center justify-between">
          <div>
            <p className="text-sm font-medium">Design system</p>
            <p className="text-xs text-neutral-500">Tune reusable project tokens.</p>
          </div>
          <button
            className={`h-7 w-12 rounded-full p-1 transition ${enabled ? 'bg-neutral-950' : 'bg-neutral-200'}`}
            onClick={onToggle}
            aria-label="Toggle design mode"
          >
            <span className={`block h-5 w-5 rounded-full bg-white transition ${enabled ? 'translate-x-5' : ''}`} />
          </button>
        </div>

        <div className="mt-5 space-y-5">
          <TokenSlider label="Radius" value="8px" width="70%" />
          <TokenSlider label="Density" value="Comfortable" width="48%" />
          <TokenSlider label="Contrast" value="AA" width="82%" />
        </div>
      </section>

      <section className="rounded-lg border border-neutral-200 bg-white p-4">
        <p className="text-sm font-medium">Theme palette</p>
        <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">
          {[
            ['Neutral', 'bg-neutral-950'],
            ['Canvas', 'bg-[#fafafa]'],
            ['Accent', 'bg-orange-500'],
            ['Success', 'bg-emerald-500'],
          ].map(([label, color]) => (
            <button key={label} className="rounded-lg border border-neutral-200 p-2 text-left hover:bg-neutral-50">
              <span className={`block h-16 rounded-md ${color}`} />
              <span className="mt-2 block text-sm">{label}</span>
            </button>
          ))}
        </div>

        <div className="mt-5 rounded-lg border border-neutral-200 bg-[#fafafa] p-4">
          <p className="text-sm font-medium">Component states</p>
          <div className="mt-3 flex flex-wrap gap-2">
            {['Default', 'Hover', 'Focused', 'Disabled'].map((state) => (
              <button key={state} className="h-8 rounded-md border border-neutral-200 bg-white px-3 text-sm">
                {state}
              </button>
            ))}
          </div>
        </div>
      </section>
    </div>
  )
}

function TokenSlider({ label, value, width }: { label: string; value: string; width: string }) {
  return (
    <div>
      <div className="mb-2 flex justify-between text-sm">
        <span>{label}</span>
        <span className="text-neutral-500">{value}</span>
      </div>
      <div className="h-2 rounded-full bg-neutral-100">
        <div className="h-full rounded-full bg-neutral-950" style={{ width }} />
      </div>
    </div>
  )
}

function DeployPanel({ open, onToggle }: { open: boolean; onToggle: () => void }) {
  return (
    <div className="mx-auto max-w-5xl rounded-lg border border-neutral-200 bg-white p-5 shadow-sm">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <p className="text-sm font-medium text-neutral-500">Production</p>
          <h2 className="mt-1 text-2xl font-semibold">Deploy to Vercel</h2>
          <p className="mt-2 max-w-2xl text-sm leading-6 text-neutral-600">
            Go live instantly, open a pull request, or push generated code to a repository.
          </p>
        </div>
        <button
          className="inline-flex h-9 min-w-[156px] items-center justify-center gap-2 whitespace-nowrap rounded-md bg-neutral-950 px-4 text-sm font-medium text-white hover:bg-neutral-800"
          onClick={onToggle}
        >
          {open ? <CheckCircle2 className="h-4 w-4" /> : <UploadCloud className="h-4 w-4" />}
          {open ? 'Deployment queued' : 'Deploy to Vercel'}
        </button>
      </div>

      <div className="mt-6 grid gap-3 md:grid-cols-3">
        {[
          ['Preview URL', 'v0-clone.vercel.app', ExternalLink],
          ['Repository', 'github.com/team/v0-clone', Github],
          ['Diagnostics', 'No blocking errors', CheckCircle2],
        ].map(([label, value, Icon]) => (
          <div key={label as string} className="rounded-lg border border-neutral-200 bg-[#fafafa] p-4">
            <Icon className="h-5 w-5 text-neutral-500" />
            <p className="mt-4 text-xs text-neutral-500">{label as string}</p>
            <p className="mt-1 truncate text-sm font-medium">{value as string}</p>
          </div>
        ))}
      </div>

      {open ? (
        <div className="mt-5 rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-950">
          Build output is ready. The mocked deployment flow now shows the same success state a v0 user expects before publishing.
        </div>
      ) : null}

      <div className="mt-5 rounded-lg border border-neutral-200">
        {['Install dependencies', 'Run type checks', 'Create preview deployment', 'Open pull request'].map((item, index) => (
          <div key={item} className="flex items-center gap-3 border-b border-neutral-200 px-4 py-3 last:border-b-0">
            <span className="flex h-6 w-6 items-center justify-center rounded-full bg-neutral-950 text-xs text-white">
              {index + 1}
            </span>
            <span className="text-sm">{item}</span>
            <CheckCircle2 className="ml-auto h-4 w-4 text-emerald-600" />
          </div>
        ))}
      </div>
    </div>
  )
}
